// Generated by jextract

package crab.newton.internal;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
public final class constants$74 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$74() {}
    public static final FunctionDescriptor NewtonCollisionGetScale$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonCollisionGetScale$MH = RuntimeHelper.downcallHandle(
        "NewtonCollisionGetScale",
        constants$74.NewtonCollisionGetScale$FUNC
    );
    public static final FunctionDescriptor NewtonDestroyCollision$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonDestroyCollision$MH = RuntimeHelper.downcallHandle(
        "NewtonDestroyCollision",
        constants$74.NewtonDestroyCollision$FUNC
    );
    public static final FunctionDescriptor NewtonCollisionGetSkinThickness$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonCollisionGetSkinThickness$MH = RuntimeHelper.downcallHandle(
        "NewtonCollisionGetSkinThickness",
        constants$74.NewtonCollisionGetSkinThickness$FUNC
    );
    public static final FunctionDescriptor NewtonCollisionSetSkinThickness$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    public static final MethodHandle NewtonCollisionSetSkinThickness$MH = RuntimeHelper.downcallHandle(
        "NewtonCollisionSetSkinThickness",
        constants$74.NewtonCollisionSetSkinThickness$FUNC
    );
    public static final FunctionDescriptor NewtonCollisionIntersectionTest$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    public static final MethodHandle NewtonCollisionIntersectionTest$MH = RuntimeHelper.downcallHandle(
        "NewtonCollisionIntersectionTest",
        constants$74.NewtonCollisionIntersectionTest$FUNC
    );
    public static final FunctionDescriptor NewtonCollisionPointDistance$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    public static final MethodHandle NewtonCollisionPointDistance$MH = RuntimeHelper.downcallHandle(
        "NewtonCollisionPointDistance",
        constants$74.NewtonCollisionPointDistance$FUNC
    );
}


