// Generated by jextract

package crab.newton.internal;

import java.lang.invoke.MethodHandle;
import java.lang.foreign.*;
import crab.newton.callbacks.*;
public final class constants$31 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$31() {}
    public static final FunctionDescriptor NewtonGetMaxThreadsCount$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonGetMaxThreadsCount$MH = RuntimeHelper.downcallHandle(
        "NewtonGetMaxThreadsCount",
        constants$31.NewtonGetMaxThreadsCount$FUNC
    );
    public static final FunctionDescriptor NewtonDispachThreadJob$task$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    public static final FunctionDescriptor NewtonDispachThreadJob$task_UP$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    public static final MethodHandle NewtonDispachThreadJob$task_UP$MH = RuntimeHelper.upcallHandle(NewtonDispachThreadJob$task.class, "apply", constants$31.NewtonDispachThreadJob$task_UP$FUNC);
    public static final FunctionDescriptor NewtonDispachThreadJob$task_DOWN$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    public static final MethodHandle NewtonDispachThreadJob$task_DOWN$MH = RuntimeHelper.downcallHandle(
        constants$31.NewtonDispachThreadJob$task_DOWN$FUNC
    );
    public static final FunctionDescriptor NewtonDispachThreadJob$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonDispachThreadJob$MH = RuntimeHelper.downcallHandle(
        "NewtonDispachThreadJob",
        constants$31.NewtonDispachThreadJob$FUNC
    );
    public static final FunctionDescriptor NewtonSyncThreadJobs$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonSyncThreadJobs$MH = RuntimeHelper.downcallHandle(
        "NewtonSyncThreadJobs",
        constants$31.NewtonSyncThreadJobs$FUNC
    );
    public static final FunctionDescriptor NewtonAtomicAdd$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    public static final MethodHandle NewtonAtomicAdd$MH = RuntimeHelper.downcallHandle(
        "NewtonAtomicAdd",
        constants$31.NewtonAtomicAdd$FUNC
    );
}


