// Generated by jextract

package crab.newton.internal;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
public class constants$9 {

	public static final FunctionDescriptor NewtonCollisionCopyConstructionCallback$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
	public static final MethodHandle NewtonCollisionCopyConstructionCallback$MH = RuntimeHelper.downcallHandle(
        constants$9.NewtonCollisionCopyConstructionCallback$FUNC, false
    );
	public static final FunctionDescriptor NewtonCollisionDestructorCallback$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
	public static final MethodHandle NewtonCollisionDestructorCallback$MH = RuntimeHelper.downcallHandle(
        constants$9.NewtonCollisionDestructorCallback$FUNC, false
    );
	public static final FunctionDescriptor NewtonTreeCollisionCallback$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
	public static final MethodHandle NewtonTreeCollisionCallback$MH = RuntimeHelper.downcallHandle(
        constants$9.NewtonTreeCollisionCallback$FUNC, false
    );
}


