// Generated by jextract

package crab.newton.internal;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
public class constants$72 {

	public static final FunctionDescriptor NewtonContactJointGetNextContact$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
	public static final MethodHandle NewtonContactJointGetNextContact$MH = RuntimeHelper.downcallHandle(
        "NewtonContactJointGetNextContact",
        constants$72.NewtonContactJointGetNextContact$FUNC, false
    );
	public static final FunctionDescriptor NewtonContactJointGetContactCount$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
	public static final MethodHandle NewtonContactJointGetContactCount$MH = RuntimeHelper.downcallHandle(
        "NewtonContactJointGetContactCount",
        constants$72.NewtonContactJointGetContactCount$FUNC, false
    );
	public static final FunctionDescriptor NewtonContactJointRemoveContact$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
	public static final MethodHandle NewtonContactJointRemoveContact$MH = RuntimeHelper.downcallHandle(
        "NewtonContactJointRemoveContact",
        constants$72.NewtonContactJointRemoveContact$FUNC, false
    );
	public static final FunctionDescriptor NewtonContactJointGetClosestDistance$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
	public static final MethodHandle NewtonContactJointGetClosestDistance$MH = RuntimeHelper.downcallHandle(
        "NewtonContactJointGetClosestDistance",
        constants$72.NewtonContactJointGetClosestDistance$FUNC, false
    );
	public static final FunctionDescriptor NewtonContactJointResetSelftJointCollision$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
	public static final MethodHandle NewtonContactJointResetSelftJointCollision$MH = RuntimeHelper.downcallHandle(
        "NewtonContactJointResetSelftJointCollision",
        constants$72.NewtonContactJointResetSelftJointCollision$FUNC, false
    );
	public static final FunctionDescriptor NewtonContactJointResetIntraJointCollision$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
	public static final MethodHandle NewtonContactJointResetIntraJointCollision$MH = RuntimeHelper.downcallHandle(
        "NewtonContactJointResetIntraJointCollision",
        constants$72.NewtonContactJointResetIntraJointCollision$FUNC, false
    );
}


