// Generated by jextract
package crab.newton.internal;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
public class constants$7 {

    public static final FunctionDescriptor NewtonUserMeshCollisionAABBTest$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonUserMeshCollisionAABBTest$MH = RuntimeHelper.downcallHandle(
        constants$7.NewtonUserMeshCollisionAABBTest$FUNC
    );
    public static final FunctionDescriptor NewtonUserMeshCollisionGetFacesInAABB$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonUserMeshCollisionGetFacesInAABB$MH = RuntimeHelper.downcallHandle(
        constants$7.NewtonUserMeshCollisionGetFacesInAABB$FUNC
    );
    public static final FunctionDescriptor NewtonUserMeshCollisionCollideCallback$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonUserMeshCollisionCollideCallback$MH = RuntimeHelper.downcallHandle(
        constants$7.NewtonUserMeshCollisionCollideCallback$FUNC
    );
}


