// Generated by jextract

package crab.newton.internal;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
public class constants$21 {

	public static final FunctionDescriptor NewtonGetFirstPlugin$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
	public static final MethodHandle NewtonGetFirstPlugin$MH = RuntimeHelper.downcallHandle(
        "NewtonGetFirstPlugin",
        constants$21.NewtonGetFirstPlugin$FUNC, false
    );
	public static final FunctionDescriptor NewtonGetPreferedPlugin$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
	public static final MethodHandle NewtonGetPreferedPlugin$MH = RuntimeHelper.downcallHandle(
        "NewtonGetPreferedPlugin",
        constants$21.NewtonGetPreferedPlugin$FUNC, false
    );
	public static final FunctionDescriptor NewtonGetNextPlugin$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
	public static final MethodHandle NewtonGetNextPlugin$MH = RuntimeHelper.downcallHandle(
        "NewtonGetNextPlugin",
        constants$21.NewtonGetNextPlugin$FUNC, false
    );
	public static final FunctionDescriptor NewtonGetPluginString$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
	public static final MethodHandle NewtonGetPluginString$MH = RuntimeHelper.downcallHandle(
        "NewtonGetPluginString",
        constants$21.NewtonGetPluginString$FUNC, false
    );
	public static final FunctionDescriptor NewtonSelectPlugin$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
	public static final MethodHandle NewtonSelectPlugin$MH = RuntimeHelper.downcallHandle(
        "NewtonSelectPlugin",
        constants$21.NewtonSelectPlugin$FUNC, false
    );
	public static final FunctionDescriptor NewtonGetContactMergeTolerance$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
	public static final MethodHandle NewtonGetContactMergeTolerance$MH = RuntimeHelper.downcallHandle(
        "NewtonGetContactMergeTolerance",
        constants$21.NewtonGetContactMergeTolerance$FUNC, false
    );
}


