// Generated by jextract

package crab.newton.internal;

import java.lang.invoke.MethodHandle;
import java.lang.foreign.*;
import crab.newton.callbacks.*;
public final class constants$112 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$112() {}
    public static final FunctionDescriptor NewtonMeshCreateFromSerialization$deserializeFunction_DOWN$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    public static final MethodHandle NewtonMeshCreateFromSerialization$deserializeFunction_DOWN$MH = RuntimeHelper.downcallHandle(
        constants$112.NewtonMeshCreateFromSerialization$deserializeFunction_DOWN$FUNC
    );
    public static final FunctionDescriptor NewtonMeshCreateFromSerialization$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonMeshCreateFromSerialization$MH = RuntimeHelper.downcallHandle(
        "NewtonMeshCreateFromSerialization",
        constants$112.NewtonMeshCreateFromSerialization$FUNC
    );
    public static final FunctionDescriptor NewtonMeshDestroy$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonMeshDestroy$MH = RuntimeHelper.downcallHandle(
        "NewtonMeshDestroy",
        constants$112.NewtonMeshDestroy$FUNC
    );
    public static final FunctionDescriptor NewtonMeshSerialize$serializeFunction$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    public static final FunctionDescriptor NewtonMeshSerialize$serializeFunction_UP$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    public static final MethodHandle NewtonMeshSerialize$serializeFunction_UP$MH = RuntimeHelper.upcallHandle(NewtonMeshSerialize$serializeFunction.class, "apply", constants$112.NewtonMeshSerialize$serializeFunction_UP$FUNC);
    public static final FunctionDescriptor NewtonMeshSerialize$serializeFunction_DOWN$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    public static final MethodHandle NewtonMeshSerialize$serializeFunction_DOWN$MH = RuntimeHelper.downcallHandle(
        constants$112.NewtonMeshSerialize$serializeFunction_DOWN$FUNC
    );
    public static final FunctionDescriptor NewtonMeshSerialize$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonMeshSerialize$MH = RuntimeHelper.downcallHandle(
        "NewtonMeshSerialize",
        constants$112.NewtonMeshSerialize$FUNC
    );
}


