// Generated by jextract

package crab.newton.internal;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
public final class constants$99 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$99() {}
    public static final FunctionDescriptor NewtonBallSetUserCallback$callback_DOWN$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    public static final MethodHandle NewtonBallSetUserCallback$callback_DOWN$MH = RuntimeHelper.downcallHandle(
        constants$99.NewtonBallSetUserCallback$callback_DOWN$FUNC
    );
    public static final FunctionDescriptor NewtonBallSetUserCallback$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonBallSetUserCallback$MH = RuntimeHelper.downcallHandle(
        "NewtonBallSetUserCallback",
        constants$99.NewtonBallSetUserCallback$FUNC
    );
    public static final FunctionDescriptor NewtonBallGetJointAngle$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonBallGetJointAngle$MH = RuntimeHelper.downcallHandle(
        "NewtonBallGetJointAngle",
        constants$99.NewtonBallGetJointAngle$FUNC
    );
    public static final FunctionDescriptor NewtonBallGetJointOmega$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonBallGetJointOmega$MH = RuntimeHelper.downcallHandle(
        "NewtonBallGetJointOmega",
        constants$99.NewtonBallGetJointOmega$FUNC
    );
    public static final FunctionDescriptor NewtonBallGetJointForce$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonBallGetJointForce$MH = RuntimeHelper.downcallHandle(
        "NewtonBallGetJointForce",
        constants$99.NewtonBallGetJointForce$FUNC
    );
    public static final FunctionDescriptor NewtonBallSetConeLimits$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    public static final MethodHandle NewtonBallSetConeLimits$MH = RuntimeHelper.downcallHandle(
        "NewtonBallSetConeLimits",
        constants$99.NewtonBallSetConeLimits$FUNC
    );
}


