// Generated by jextract
package crab.newton.internal;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
public class constants$2 {

    public static final FunctionDescriptor NewtonWorldListenerDebugCallback$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonWorldListenerDebugCallback$MH = RuntimeHelper.downcallHandle(
        constants$2.NewtonWorldListenerDebugCallback$FUNC
    );
    public static final FunctionDescriptor NewtonWorldListenerBodyDestroyCallback$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonWorldListenerBodyDestroyCallback$MH = RuntimeHelper.downcallHandle(
        constants$2.NewtonWorldListenerBodyDestroyCallback$FUNC
    );
    public static final FunctionDescriptor NewtonWorldUpdateListenerCallback$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    public static final MethodHandle NewtonWorldUpdateListenerCallback$MH = RuntimeHelper.downcallHandle(
        constants$2.NewtonWorldUpdateListenerCallback$FUNC
    );
}


