// Generated by jextract

package crab.newton.internal;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
public final class constants$24 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$24() {}
    public static final FunctionDescriptor NewtonSetParallelSolverOnLargeIsland$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    public static final MethodHandle NewtonSetParallelSolverOnLargeIsland$MH = RuntimeHelper.downcallHandle(
        "NewtonSetParallelSolverOnLargeIsland",
        constants$24.NewtonSetParallelSolverOnLargeIsland$FUNC
    );
    public static final FunctionDescriptor NewtonGetParallelSolverOnLargeIsland$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonGetParallelSolverOnLargeIsland$MH = RuntimeHelper.downcallHandle(
        "NewtonGetParallelSolverOnLargeIsland",
        constants$24.NewtonGetParallelSolverOnLargeIsland$FUNC
    );
    public static final FunctionDescriptor NewtonGetBroadphaseAlgorithm$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonGetBroadphaseAlgorithm$MH = RuntimeHelper.downcallHandle(
        "NewtonGetBroadphaseAlgorithm",
        constants$24.NewtonGetBroadphaseAlgorithm$FUNC
    );
    public static final FunctionDescriptor NewtonSelectBroadphaseAlgorithm$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    public static final MethodHandle NewtonSelectBroadphaseAlgorithm$MH = RuntimeHelper.downcallHandle(
        "NewtonSelectBroadphaseAlgorithm",
        constants$24.NewtonSelectBroadphaseAlgorithm$FUNC
    );
    public static final FunctionDescriptor NewtonResetBroadphase$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonResetBroadphase$MH = RuntimeHelper.downcallHandle(
        "NewtonResetBroadphase",
        constants$24.NewtonResetBroadphase$FUNC
    );
    public static final FunctionDescriptor NewtonUpdate$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    public static final MethodHandle NewtonUpdate$MH = RuntimeHelper.downcallHandle(
        "NewtonUpdate",
        constants$24.NewtonUpdate$FUNC
    );
}


