// Generated by jextract

package crab.newton.internal;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
public class constants$26 {

	public static final FunctionDescriptor NewtonSetThreadsCount$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
	public static final MethodHandle NewtonSetThreadsCount$MH = RuntimeHelper.downcallHandle(
        "NewtonSetThreadsCount",
        constants$26.NewtonSetThreadsCount$FUNC, false
    );
	public static final FunctionDescriptor NewtonGetThreadsCount$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
	public static final MethodHandle NewtonGetThreadsCount$MH = RuntimeHelper.downcallHandle(
        "NewtonGetThreadsCount",
        constants$26.NewtonGetThreadsCount$FUNC, false
    );
	public static final FunctionDescriptor NewtonGetMaxThreadsCount$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
	public static final MethodHandle NewtonGetMaxThreadsCount$MH = RuntimeHelper.downcallHandle(
        "NewtonGetMaxThreadsCount",
        constants$26.NewtonGetMaxThreadsCount$FUNC, false
    );
	public static final FunctionDescriptor NewtonDispachThreadJob$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
	public static final MethodHandle NewtonDispachThreadJob$MH = RuntimeHelper.downcallHandle(
        "NewtonDispachThreadJob",
        constants$26.NewtonDispachThreadJob$FUNC, false
    );
	public static final FunctionDescriptor NewtonSyncThreadJobs$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
	public static final MethodHandle NewtonSyncThreadJobs$MH = RuntimeHelper.downcallHandle(
        "NewtonSyncThreadJobs",
        constants$26.NewtonSyncThreadJobs$FUNC, false
    );
	public static final FunctionDescriptor NewtonAtomicAdd$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
	public static final MethodHandle NewtonAtomicAdd$MH = RuntimeHelper.downcallHandle(
        "NewtonAtomicAdd",
        constants$26.NewtonAtomicAdd$FUNC, false
    );
}


