// Generated by jextract

package crab.newton.internal;

import java.lang.invoke.MethodHandle;
import java.lang.foreign.*;
import crab.newton.callbacks.*;
public final class constants$67 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$67() {}
    public static final FunctionDescriptor NewtonCreateCollisionFromSerialization$deserializeFunction_DOWN$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    public static final MethodHandle NewtonCreateCollisionFromSerialization$deserializeFunction_DOWN$MH = RuntimeHelper.downcallHandle(
        constants$67.NewtonCreateCollisionFromSerialization$deserializeFunction_DOWN$FUNC
    );
    public static final FunctionDescriptor NewtonCreateCollisionFromSerialization$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonCreateCollisionFromSerialization$MH = RuntimeHelper.downcallHandle(
        "NewtonCreateCollisionFromSerialization",
        constants$67.NewtonCreateCollisionFromSerialization$FUNC
    );
    public static final FunctionDescriptor NewtonCollisionSerialize$serializeFunction$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    public static final FunctionDescriptor NewtonCollisionSerialize$serializeFunction_UP$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    public static final MethodHandle NewtonCollisionSerialize$serializeFunction_UP$MH = RuntimeHelper.upcallHandle(NewtonCollisionSerialize$serializeFunction.class, "apply", constants$67.NewtonCollisionSerialize$serializeFunction_UP$FUNC);
    public static final FunctionDescriptor NewtonCollisionSerialize$serializeFunction_DOWN$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    public static final MethodHandle NewtonCollisionSerialize$serializeFunction_DOWN$MH = RuntimeHelper.downcallHandle(
        constants$67.NewtonCollisionSerialize$serializeFunction_DOWN$FUNC
    );
    public static final FunctionDescriptor NewtonCollisionSerialize$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonCollisionSerialize$MH = RuntimeHelper.downcallHandle(
        "NewtonCollisionSerialize",
        constants$67.NewtonCollisionSerialize$FUNC
    );
    public static final FunctionDescriptor NewtonCollisionGetInfo$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonCollisionGetInfo$MH = RuntimeHelper.downcallHandle(
        "NewtonCollisionGetInfo",
        constants$67.NewtonCollisionGetInfo$FUNC
    );
}


