// Generated by jextract

package crab.newton.internal;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
public class constants$4 {

	public static final FunctionDescriptor NewtonDeserializeCallback$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
	public static final MethodHandle NewtonDeserializeCallback$MH = RuntimeHelper.downcallHandle(
        constants$4.NewtonDeserializeCallback$FUNC, false
    );
	public static final FunctionDescriptor NewtonOnBodySerializationCallback$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
	public static final MethodHandle NewtonOnBodySerializationCallback$MH = RuntimeHelper.downcallHandle(
        constants$4.NewtonOnBodySerializationCallback$FUNC, false
    );
	public static final FunctionDescriptor NewtonOnBodyDeserializationCallback$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
	public static final MethodHandle NewtonOnBodyDeserializationCallback$MH = RuntimeHelper.downcallHandle(
        constants$4.NewtonOnBodyDeserializationCallback$FUNC, false
    );
}


