// Generated by jextract
package crab.newton.internal;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
public class constants$14 {

    public static final FunctionDescriptor NewtonOnContactGeneration$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    public static final MethodHandle NewtonOnContactGeneration$MH = RuntimeHelper.downcallHandle(
        constants$14.NewtonOnContactGeneration$FUNC
    );
    public static final FunctionDescriptor NewtonBodyIterator$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonBodyIterator$MH = RuntimeHelper.downcallHandle(
        constants$14.NewtonBodyIterator$FUNC
    );
    public static final FunctionDescriptor NewtonJointIterator$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonJointIterator$MH = RuntimeHelper.downcallHandle(
        constants$14.NewtonJointIterator$FUNC
    );
}


