// Generated by jextract

package crab.newton.internal;

import java.lang.invoke.MethodHandle;
import java.lang.foreign.*;
import crab.newton.callbacks.*;
public final class constants$15 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$15() {}
    public static final FunctionDescriptor NewtonCollisionIterator$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    public static final FunctionDescriptor NewtonCollisionIterator_UP$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    public static final MethodHandle NewtonCollisionIterator_UP$MH = RuntimeHelper.upcallHandle(NewtonCollisionIterator.class, "apply", constants$15.NewtonCollisionIterator_UP$FUNC);
    public static final FunctionDescriptor NewtonCollisionIterator_DOWN$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    public static final MethodHandle NewtonCollisionIterator_DOWN$MH = RuntimeHelper.downcallHandle(
        constants$15.NewtonCollisionIterator_DOWN$FUNC
    );
    public static final FunctionDescriptor NewtonBallCallback$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    public static final FunctionDescriptor NewtonBallCallback_UP$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    public static final MethodHandle NewtonBallCallback_UP$MH = RuntimeHelper.upcallHandle(NewtonBallCallback.class, "apply", constants$15.NewtonBallCallback_UP$FUNC);
    public static final FunctionDescriptor NewtonBallCallback_DOWN$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    public static final MethodHandle NewtonBallCallback_DOWN$MH = RuntimeHelper.downcallHandle(
        constants$15.NewtonBallCallback_DOWN$FUNC
    );
    public static final FunctionDescriptor NewtonHingeCallback$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final FunctionDescriptor NewtonHingeCallback_UP$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonHingeCallback_UP$MH = RuntimeHelper.upcallHandle(NewtonHingeCallback.class, "apply", constants$15.NewtonHingeCallback_UP$FUNC);
    public static final FunctionDescriptor NewtonHingeCallback_DOWN$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonHingeCallback_DOWN$MH = RuntimeHelper.downcallHandle(
        constants$15.NewtonHingeCallback_DOWN$FUNC
    );
}


