// Generated by jextract

package crab.newton.internal;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
public class constants$19 {

	public static final FunctionDescriptor NewtonGetMemoryUsed$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT);
	public static final MethodHandle NewtonGetMemoryUsed$MH = RuntimeHelper.downcallHandle(
        "NewtonGetMemoryUsed",
        constants$19.NewtonGetMemoryUsed$FUNC, true
    );
	public static final FunctionDescriptor NewtonSetMemorySystem$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
	public static final MethodHandle NewtonSetMemorySystem$MH = RuntimeHelper.downcallHandle(
        "NewtonSetMemorySystem",
        constants$19.NewtonSetMemorySystem$FUNC, false
    );
	public static final FunctionDescriptor NewtonCreate$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT);
	public static final MethodHandle NewtonCreate$MH = RuntimeHelper.downcallHandle(
        "NewtonCreate",
        constants$19.NewtonCreate$FUNC, true
    );
	public static final FunctionDescriptor NewtonDestroy$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
	public static final MethodHandle NewtonDestroy$MH = RuntimeHelper.downcallHandle(
        "NewtonDestroy",
        constants$19.NewtonDestroy$FUNC, false
    );
	public static final FunctionDescriptor NewtonDestroyAllBodies$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
	public static final MethodHandle NewtonDestroyAllBodies$MH = RuntimeHelper.downcallHandle(
        "NewtonDestroyAllBodies",
        constants$19.NewtonDestroyAllBodies$FUNC, false
    );
	public static final FunctionDescriptor NewtonGetPostUpdateCallback$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
	public static final MethodHandle NewtonGetPostUpdateCallback$MH = RuntimeHelper.downcallHandle(
        "NewtonGetPostUpdateCallback",
        constants$19.NewtonGetPostUpdateCallback$FUNC, false
    );
}


