// Generated by jextract
package crab.newton.internal;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
public class constants$60 {

    public static final FunctionDescriptor NewtonBodyAddTorque$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonBodyAddTorque$MH = RuntimeHelper.downcallHandle(
        "NewtonBodyAddTorque",
        constants$60.NewtonBodyAddTorque$FUNC
    );
    public static final FunctionDescriptor NewtonBodySetCentreOfMass$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonBodySetCentreOfMass$MH = RuntimeHelper.downcallHandle(
        "NewtonBodySetCentreOfMass",
        constants$60.NewtonBodySetCentreOfMass$FUNC
    );
    public static final FunctionDescriptor NewtonBodySetMassMatrix$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    public static final MethodHandle NewtonBodySetMassMatrix$MH = RuntimeHelper.downcallHandle(
        "NewtonBodySetMassMatrix",
        constants$60.NewtonBodySetMassMatrix$FUNC
    );
    public static final FunctionDescriptor NewtonBodySetFullMassMatrix$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonBodySetFullMassMatrix$MH = RuntimeHelper.downcallHandle(
        "NewtonBodySetFullMassMatrix",
        constants$60.NewtonBodySetFullMassMatrix$FUNC
    );
    public static final FunctionDescriptor NewtonBodySetMassProperties$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonBodySetMassProperties$MH = RuntimeHelper.downcallHandle(
        "NewtonBodySetMassProperties",
        constants$60.NewtonBodySetMassProperties$FUNC
    );
    public static final FunctionDescriptor NewtonBodySetMatrix$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonBodySetMatrix$MH = RuntimeHelper.downcallHandle(
        "NewtonBodySetMatrix",
        constants$60.NewtonBodySetMatrix$FUNC
    );
}


