// Generated by jextract

package crab.newton.internal;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
public class constants$46 {

	public static final FunctionDescriptor NewtonFracturedCompoundCollisionGetVertexNormals$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
	public static final MethodHandle NewtonFracturedCompoundCollisionGetVertexNormals$MH = RuntimeHelper.downcallHandle(
        "NewtonFracturedCompoundCollisionGetVertexNormals",
        constants$46.NewtonFracturedCompoundCollisionGetVertexNormals$FUNC, false
    );
	public static final FunctionDescriptor NewtonFracturedCompoundCollisionGetVertexUVs$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
	public static final MethodHandle NewtonFracturedCompoundCollisionGetVertexUVs$MH = RuntimeHelper.downcallHandle(
        "NewtonFracturedCompoundCollisionGetVertexUVs",
        constants$46.NewtonFracturedCompoundCollisionGetVertexUVs$FUNC, false
    );
	public static final FunctionDescriptor NewtonFracturedCompoundMeshPartGetIndexStream$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
	public static final MethodHandle NewtonFracturedCompoundMeshPartGetIndexStream$MH = RuntimeHelper.downcallHandle(
        "NewtonFracturedCompoundMeshPartGetIndexStream",
        constants$46.NewtonFracturedCompoundMeshPartGetIndexStream$FUNC, false
    );
	public static final FunctionDescriptor NewtonFracturedCompoundMeshPartGetFirstSegment$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
	public static final MethodHandle NewtonFracturedCompoundMeshPartGetFirstSegment$MH = RuntimeHelper.downcallHandle(
        "NewtonFracturedCompoundMeshPartGetFirstSegment",
        constants$46.NewtonFracturedCompoundMeshPartGetFirstSegment$FUNC, false
    );
	public static final FunctionDescriptor NewtonFracturedCompoundMeshPartGetNextSegment$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
	public static final MethodHandle NewtonFracturedCompoundMeshPartGetNextSegment$MH = RuntimeHelper.downcallHandle(
        "NewtonFracturedCompoundMeshPartGetNextSegment",
        constants$46.NewtonFracturedCompoundMeshPartGetNextSegment$FUNC, false
    );
	public static final FunctionDescriptor NewtonFracturedCompoundMeshPartGetMaterial$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
	public static final MethodHandle NewtonFracturedCompoundMeshPartGetMaterial$MH = RuntimeHelper.downcallHandle(
        "NewtonFracturedCompoundMeshPartGetMaterial",
        constants$46.NewtonFracturedCompoundMeshPartGetMaterial$FUNC, false
    );
}


