// Generated by jextract
package crab.newton.internal;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
public class constants$97 {

    public static final FunctionDescriptor NewtonMeshHasVertexColorChannel$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonMeshHasVertexColorChannel$MH = RuntimeHelper.downcallHandle(
        "NewtonMeshHasVertexColorChannel",
        constants$97.NewtonMeshHasVertexColorChannel$FUNC
    );
    public static final FunctionDescriptor NewtonMeshBeginHandle$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonMeshBeginHandle$MH = RuntimeHelper.downcallHandle(
        "NewtonMeshBeginHandle",
        constants$97.NewtonMeshBeginHandle$FUNC
    );
    public static final FunctionDescriptor NewtonMeshEndHandle$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonMeshEndHandle$MH = RuntimeHelper.downcallHandle(
        "NewtonMeshEndHandle",
        constants$97.NewtonMeshEndHandle$FUNC
    );
    public static final FunctionDescriptor NewtonMeshFirstMaterial$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonMeshFirstMaterial$MH = RuntimeHelper.downcallHandle(
        "NewtonMeshFirstMaterial",
        constants$97.NewtonMeshFirstMaterial$FUNC
    );
    public static final FunctionDescriptor NewtonMeshNextMaterial$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    public static final MethodHandle NewtonMeshNextMaterial$MH = RuntimeHelper.downcallHandle(
        "NewtonMeshNextMaterial",
        constants$97.NewtonMeshNextMaterial$FUNC
    );
    public static final FunctionDescriptor NewtonMeshMaterialGetMaterial$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    public static final MethodHandle NewtonMeshMaterialGetMaterial$MH = RuntimeHelper.downcallHandle(
        "NewtonMeshMaterialGetMaterial",
        constants$97.NewtonMeshMaterialGetMaterial$FUNC
    );
}


