// Generated by jextract

package crab.newton.internal;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
public class constants$85 {

	public static final FunctionDescriptor NewtonUserJointGetRowAcceleration$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
	public static final MethodHandle NewtonUserJointGetRowAcceleration$MH = RuntimeHelper.downcallHandle(
        "NewtonUserJointGetRowAcceleration",
        constants$85.NewtonUserJointGetRowAcceleration$FUNC, false
    );
	public static final FunctionDescriptor NewtonUserJointGetRowJacobian$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
	public static final MethodHandle NewtonUserJointGetRowJacobian$MH = RuntimeHelper.downcallHandle(
        "NewtonUserJointGetRowJacobian",
        constants$85.NewtonUserJointGetRowJacobian$FUNC, false
    );
	public static final FunctionDescriptor NewtonUserJointSetRowAcceleration$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
	public static final MethodHandle NewtonUserJointSetRowAcceleration$MH = RuntimeHelper.downcallHandle(
        "NewtonUserJointSetRowAcceleration",
        constants$85.NewtonUserJointSetRowAcceleration$FUNC, false
    );
	public static final FunctionDescriptor NewtonUserJointSetRowMassDependentSpringDamperAcceleration$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
	public static final MethodHandle NewtonUserJointSetRowMassDependentSpringDamperAcceleration$MH = RuntimeHelper.downcallHandle(
        "NewtonUserJointSetRowMassDependentSpringDamperAcceleration",
        constants$85.NewtonUserJointSetRowMassDependentSpringDamperAcceleration$FUNC, false
    );
	public static final FunctionDescriptor NewtonUserJointSetRowMassIndependentSpringDamperAcceleration$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
	public static final MethodHandle NewtonUserJointSetRowMassIndependentSpringDamperAcceleration$MH = RuntimeHelper.downcallHandle(
        "NewtonUserJointSetRowMassIndependentSpringDamperAcceleration",
        constants$85.NewtonUserJointSetRowMassIndependentSpringDamperAcceleration$FUNC, false
    );
	public static final FunctionDescriptor NewtonUserJointSetRowStiffness$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
	public static final MethodHandle NewtonUserJointSetRowStiffness$MH = RuntimeHelper.downcallHandle(
        "NewtonUserJointSetRowStiffness",
        constants$85.NewtonUserJointSetRowStiffness$FUNC, false
    );
}


