// Generated by jextract

package crab.newton.internal;

import java.lang.invoke.MethodHandle;
import java.lang.foreign.*;
import crab.newton.callbacks.*;
public final class constants$46 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$46() {}
    public static final FunctionDescriptor NewtonMaterialSetCollisionCallback$process$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    public static final FunctionDescriptor NewtonMaterialSetCollisionCallback$process_UP$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    public static final MethodHandle NewtonMaterialSetCollisionCallback$process_UP$MH = RuntimeHelper.upcallHandle(NewtonMaterialSetCollisionCallback$process.class, "apply", constants$46.NewtonMaterialSetCollisionCallback$process_UP$FUNC);
    public static final FunctionDescriptor NewtonMaterialSetCollisionCallback$process_DOWN$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    public static final MethodHandle NewtonMaterialSetCollisionCallback$process_DOWN$MH = RuntimeHelper.downcallHandle(
        constants$46.NewtonMaterialSetCollisionCallback$process_DOWN$FUNC
    );
    public static final FunctionDescriptor NewtonMaterialSetCollisionCallback$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonMaterialSetCollisionCallback$MH = RuntimeHelper.downcallHandle(
        "NewtonMaterialSetCollisionCallback",
        constants$46.NewtonMaterialSetCollisionCallback$FUNC
    );
    public static final FunctionDescriptor NewtonMaterialSetDefaultSoftness$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    public static final MethodHandle NewtonMaterialSetDefaultSoftness$MH = RuntimeHelper.downcallHandle(
        "NewtonMaterialSetDefaultSoftness",
        constants$46.NewtonMaterialSetDefaultSoftness$FUNC
    );
    public static final FunctionDescriptor NewtonMaterialSetDefaultElasticity$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    public static final MethodHandle NewtonMaterialSetDefaultElasticity$MH = RuntimeHelper.downcallHandle(
        "NewtonMaterialSetDefaultElasticity",
        constants$46.NewtonMaterialSetDefaultElasticity$FUNC
    );
    public static final FunctionDescriptor NewtonMaterialSetDefaultCollidable$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    public static final MethodHandle NewtonMaterialSetDefaultCollidable$MH = RuntimeHelper.downcallHandle(
        "NewtonMaterialSetDefaultCollidable",
        constants$46.NewtonMaterialSetDefaultCollidable$FUNC
    );
}


