// Generated by jextract
package crab.newton.internal;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
public class constants$75 {

    public static final FunctionDescriptor NewtonJointGetStiffness$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonJointGetStiffness$MH = RuntimeHelper.downcallHandle(
        "NewtonJointGetStiffness",
        constants$75.NewtonJointGetStiffness$FUNC
    );
    public static final FunctionDescriptor NewtonJointSetStiffness$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    public static final MethodHandle NewtonJointSetStiffness$MH = RuntimeHelper.downcallHandle(
        "NewtonJointSetStiffness",
        constants$75.NewtonJointSetStiffness$FUNC
    );
    public static final FunctionDescriptor NewtonDestroyJoint$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonDestroyJoint$MH = RuntimeHelper.downcallHandle(
        "NewtonDestroyJoint",
        constants$75.NewtonDestroyJoint$FUNC
    );
    public static final FunctionDescriptor NewtonJointSetDestructor$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonJointSetDestructor$MH = RuntimeHelper.downcallHandle(
        "NewtonJointSetDestructor",
        constants$75.NewtonJointSetDestructor$FUNC
    );
    public static final FunctionDescriptor NewtonJointIsActive$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonJointIsActive$MH = RuntimeHelper.downcallHandle(
        "NewtonJointIsActive",
        constants$75.NewtonJointIsActive$FUNC
    );
    public static final FunctionDescriptor NewtonCreateMassSpringDamperSystem$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonCreateMassSpringDamperSystem$MH = RuntimeHelper.downcallHandle(
        "NewtonCreateMassSpringDamperSystem",
        constants$75.NewtonCreateMassSpringDamperSystem$FUNC
    );
}


