// Generated by jextract

package crab.newton.internal;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
public final class constants$60 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$60() {}
    public static final FunctionDescriptor NewtonFracturedCompoundNeighborNodeList$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    public static final MethodHandle NewtonFracturedCompoundNeighborNodeList$MH = RuntimeHelper.downcallHandle(
        "NewtonFracturedCompoundNeighborNodeList",
        constants$60.NewtonFracturedCompoundNeighborNodeList$FUNC
    );
    public static final FunctionDescriptor NewtonFracturedCompoundGetMainMesh$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonFracturedCompoundGetMainMesh$MH = RuntimeHelper.downcallHandle(
        "NewtonFracturedCompoundGetMainMesh",
        constants$60.NewtonFracturedCompoundGetMainMesh$FUNC
    );
    public static final FunctionDescriptor NewtonFracturedCompoundGetFirstSubMesh$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonFracturedCompoundGetFirstSubMesh$MH = RuntimeHelper.downcallHandle(
        "NewtonFracturedCompoundGetFirstSubMesh",
        constants$60.NewtonFracturedCompoundGetFirstSubMesh$FUNC
    );
    public static final FunctionDescriptor NewtonFracturedCompoundGetNextSubMesh$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonFracturedCompoundGetNextSubMesh$MH = RuntimeHelper.downcallHandle(
        "NewtonFracturedCompoundGetNextSubMesh",
        constants$60.NewtonFracturedCompoundGetNextSubMesh$FUNC
    );
    public static final FunctionDescriptor NewtonFracturedCompoundCollisionGetVertexCount$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonFracturedCompoundCollisionGetVertexCount$MH = RuntimeHelper.downcallHandle(
        "NewtonFracturedCompoundCollisionGetVertexCount",
        constants$60.NewtonFracturedCompoundCollisionGetVertexCount$FUNC
    );
    public static final FunctionDescriptor NewtonFracturedCompoundCollisionGetVertexPositions$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonFracturedCompoundCollisionGetVertexPositions$MH = RuntimeHelper.downcallHandle(
        "NewtonFracturedCompoundCollisionGetVertexPositions",
        constants$60.NewtonFracturedCompoundCollisionGetVertexPositions$FUNC
    );
}


