// Generated by jextract

package crab.newton.internal;

import java.lang.invoke.MethodHandle;
import java.lang.foreign.*;
import crab.newton.callbacks.*;
public final class constants$38 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$38() {}
    public static final FunctionDescriptor NewtonWorldListenerGetBodyDestroyCallback$return_DOWN$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonWorldListenerGetBodyDestroyCallback$return_DOWN$MH = RuntimeHelper.downcallHandle(
        constants$38.NewtonWorldListenerGetBodyDestroyCallback$return_DOWN$FUNC
    );
    public static final FunctionDescriptor NewtonWorldListenerGetBodyDestroyCallback$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonWorldListenerGetBodyDestroyCallback$MH = RuntimeHelper.downcallHandle(
        "NewtonWorldListenerGetBodyDestroyCallback",
        constants$38.NewtonWorldListenerGetBodyDestroyCallback$FUNC
    );
    public static final FunctionDescriptor NewtonWorldSetDestructorCallback$destructor$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    public static final FunctionDescriptor NewtonWorldSetDestructorCallback$destructor_UP$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonWorldSetDestructorCallback$destructor_UP$MH = RuntimeHelper.upcallHandle(NewtonWorldSetDestructorCallback$destructor.class, "apply", constants$38.NewtonWorldSetDestructorCallback$destructor_UP$FUNC);
    public static final FunctionDescriptor NewtonWorldSetDestructorCallback$destructor_DOWN$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonWorldSetDestructorCallback$destructor_DOWN$MH = RuntimeHelper.downcallHandle(
        constants$38.NewtonWorldSetDestructorCallback$destructor_DOWN$FUNC
    );
    public static final FunctionDescriptor NewtonWorldSetDestructorCallback$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonWorldSetDestructorCallback$MH = RuntimeHelper.downcallHandle(
        "NewtonWorldSetDestructorCallback",
        constants$38.NewtonWorldSetDestructorCallback$FUNC
    );
    public static final FunctionDescriptor NewtonWorldGetDestructorCallback$return$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    public static final FunctionDescriptor NewtonWorldGetDestructorCallback$return_UP$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonWorldGetDestructorCallback$return_UP$MH = RuntimeHelper.upcallHandle(NewtonWorldGetDestructorCallback$return.class, "apply", constants$38.NewtonWorldGetDestructorCallback$return_UP$FUNC);
}


