// Generated by jextract
package crab.newton.internal;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
public class constants$24 {

    public static final FunctionDescriptor NewtonGetNumberOfSubsteps$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonGetNumberOfSubsteps$MH = RuntimeHelper.downcallHandle(
        "NewtonGetNumberOfSubsteps",
        constants$24.NewtonGetNumberOfSubsteps$FUNC
    );
    public static final FunctionDescriptor NewtonSetNumberOfSubsteps$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    public static final MethodHandle NewtonSetNumberOfSubsteps$MH = RuntimeHelper.downcallHandle(
        "NewtonSetNumberOfSubsteps",
        constants$24.NewtonSetNumberOfSubsteps$FUNC
    );
    public static final FunctionDescriptor NewtonGetLastUpdateTime$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonGetLastUpdateTime$MH = RuntimeHelper.downcallHandle(
        "NewtonGetLastUpdateTime",
        constants$24.NewtonGetLastUpdateTime$FUNC
    );
    public static final FunctionDescriptor NewtonSerializeToFile$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonSerializeToFile$MH = RuntimeHelper.downcallHandle(
        "NewtonSerializeToFile",
        constants$24.NewtonSerializeToFile$FUNC
    );
    public static final FunctionDescriptor NewtonDeserializeFromFile$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonDeserializeFromFile$MH = RuntimeHelper.downcallHandle(
        "NewtonDeserializeFromFile",
        constants$24.NewtonDeserializeFromFile$FUNC
    );
    public static final FunctionDescriptor NewtonSerializeScene$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonSerializeScene$MH = RuntimeHelper.downcallHandle(
        "NewtonSerializeScene",
        constants$24.NewtonSerializeScene$FUNC
    );
}


