// Generated by jextract

package crab.newton.internal;

import java.lang.invoke.MethodHandle;
import java.lang.foreign.*;
import crab.newton.callbacks.*;
public final class constants$98 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$98() {}
    public static final FunctionDescriptor NewtonCreateDeformableSolid$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    public static final MethodHandle NewtonCreateDeformableSolid$MH = RuntimeHelper.downcallHandle(
        "NewtonCreateDeformableSolid",
        constants$98.NewtonCreateDeformableSolid$FUNC
    );
    public static final FunctionDescriptor NewtonDeformableMeshGetParticleCount$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonDeformableMeshGetParticleCount$MH = RuntimeHelper.downcallHandle(
        "NewtonDeformableMeshGetParticleCount",
        constants$98.NewtonDeformableMeshGetParticleCount$FUNC
    );
    public static final FunctionDescriptor NewtonDeformableMeshGetParticleStrideInBytes$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonDeformableMeshGetParticleStrideInBytes$MH = RuntimeHelper.downcallHandle(
        "NewtonDeformableMeshGetParticleStrideInBytes",
        constants$98.NewtonDeformableMeshGetParticleStrideInBytes$FUNC
    );
    public static final FunctionDescriptor NewtonDeformableMeshGetParticleArray$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonDeformableMeshGetParticleArray$MH = RuntimeHelper.downcallHandle(
        "NewtonDeformableMeshGetParticleArray",
        constants$98.NewtonDeformableMeshGetParticleArray$FUNC
    );
    public static final FunctionDescriptor NewtonConstraintCreateBall$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonConstraintCreateBall$MH = RuntimeHelper.downcallHandle(
        "NewtonConstraintCreateBall",
        constants$98.NewtonConstraintCreateBall$FUNC
    );
    public static final FunctionDescriptor NewtonBallSetUserCallback$callback$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    public static final FunctionDescriptor NewtonBallSetUserCallback$callback_UP$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    public static final MethodHandle NewtonBallSetUserCallback$callback_UP$MH = RuntimeHelper.upcallHandle(NewtonBallSetUserCallback$callback.class, "apply", constants$98.NewtonBallSetUserCallback$callback_UP$FUNC);
}


