// Generated by jextract

package crab.newton.internal;

import java.lang.invoke.MethodHandle;
import java.lang.foreign.*;
import crab.newton.callbacks.*;
public final class constants$70 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$70() {}
    public static final FunctionDescriptor NewtonTreeCollisionGetFaceAttribute$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    public static final MethodHandle NewtonTreeCollisionGetFaceAttribute$MH = RuntimeHelper.downcallHandle(
        "NewtonTreeCollisionGetFaceAttribute",
        constants$70.NewtonTreeCollisionGetFaceAttribute$FUNC
    );
    public static final FunctionDescriptor NewtonTreeCollisionSetFaceAttribute$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    public static final MethodHandle NewtonTreeCollisionSetFaceAttribute$MH = RuntimeHelper.downcallHandle(
        "NewtonTreeCollisionSetFaceAttribute",
        constants$70.NewtonTreeCollisionSetFaceAttribute$FUNC
    );
    public static final FunctionDescriptor NewtonTreeCollisionForEachFace$forEachFaceCallback$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    public static final FunctionDescriptor NewtonTreeCollisionForEachFace$forEachFaceCallback_UP$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    public static final MethodHandle NewtonTreeCollisionForEachFace$forEachFaceCallback_UP$MH = RuntimeHelper.upcallHandle(NewtonTreeCollisionForEachFace$forEachFaceCallback.class, "apply", constants$70.NewtonTreeCollisionForEachFace$forEachFaceCallback_UP$FUNC);
    public static final FunctionDescriptor NewtonTreeCollisionForEachFace$forEachFaceCallback_DOWN$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    public static final MethodHandle NewtonTreeCollisionForEachFace$forEachFaceCallback_DOWN$MH = RuntimeHelper.downcallHandle(
        constants$70.NewtonTreeCollisionForEachFace$forEachFaceCallback_DOWN$FUNC
    );
    public static final FunctionDescriptor NewtonTreeCollisionForEachFace$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonTreeCollisionForEachFace$MH = RuntimeHelper.downcallHandle(
        "NewtonTreeCollisionForEachFace",
        constants$70.NewtonTreeCollisionForEachFace$FUNC
    );
    public static final FunctionDescriptor NewtonTreeCollisionGetVertexListTriangleListInAABB$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonTreeCollisionGetVertexListTriangleListInAABB$MH = RuntimeHelper.downcallHandle(
        "NewtonTreeCollisionGetVertexListTriangleListInAABB",
        constants$70.NewtonTreeCollisionGetVertexListTriangleListInAABB$FUNC
    );
}


