// Generated by jextract

package crab.newton.internal;

import java.lang.invoke.MethodHandle;
import java.lang.foreign.*;
import crab.newton.callbacks.*;
public final class constants$22 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$22() {}
    public static final FunctionDescriptor NewtonUnloadPlugins$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonUnloadPlugins$MH = RuntimeHelper.downcallHandle(
        "NewtonUnloadPlugins",
        constants$22.NewtonUnloadPlugins$FUNC
    );
    public static final FunctionDescriptor NewtonCurrentPlugin$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonCurrentPlugin$MH = RuntimeHelper.downcallHandle(
        "NewtonCurrentPlugin",
        constants$22.NewtonCurrentPlugin$FUNC
    );
    public static final FunctionDescriptor NewtonGetFirstPlugin$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonGetFirstPlugin$MH = RuntimeHelper.downcallHandle(
        "NewtonGetFirstPlugin",
        constants$22.NewtonGetFirstPlugin$FUNC
    );
    public static final FunctionDescriptor NewtonGetPreferedPlugin$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonGetPreferedPlugin$MH = RuntimeHelper.downcallHandle(
        "NewtonGetPreferedPlugin",
        constants$22.NewtonGetPreferedPlugin$FUNC
    );
    public static final FunctionDescriptor NewtonGetNextPlugin$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonGetNextPlugin$MH = RuntimeHelper.downcallHandle(
        "NewtonGetNextPlugin",
        constants$22.NewtonGetNextPlugin$FUNC
    );
    public static final FunctionDescriptor NewtonGetPluginString$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonGetPluginString$MH = RuntimeHelper.downcallHandle(
        "NewtonGetPluginString",
        constants$22.NewtonGetPluginString$FUNC
    );
}


