// Generated by jextract
package crab.newton.internal;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
public class constants$87 {

    public static final FunctionDescriptor NewtonMeshCreateTetrahedraIsoSurface$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonMeshCreateTetrahedraIsoSurface$MH = RuntimeHelper.downcallHandle(
        "NewtonMeshCreateTetrahedraIsoSurface",
        constants$87.NewtonMeshCreateTetrahedraIsoSurface$FUNC
    );
    public static final FunctionDescriptor NewtonMeshCreateConvexHull$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    public static final MethodHandle NewtonMeshCreateConvexHull$MH = RuntimeHelper.downcallHandle(
        "NewtonMeshCreateConvexHull",
        constants$87.NewtonMeshCreateConvexHull$FUNC
    );
    public static final FunctionDescriptor NewtonMeshCreateVoronoiConvexDecomposition$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonMeshCreateVoronoiConvexDecomposition$MH = RuntimeHelper.downcallHandle(
        "NewtonMeshCreateVoronoiConvexDecomposition",
        constants$87.NewtonMeshCreateVoronoiConvexDecomposition$FUNC
    );
    public static final FunctionDescriptor NewtonMeshCreateFromSerialization$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonMeshCreateFromSerialization$MH = RuntimeHelper.downcallHandle(
        "NewtonMeshCreateFromSerialization",
        constants$87.NewtonMeshCreateFromSerialization$FUNC
    );
    public static final FunctionDescriptor NewtonMeshDestroy$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonMeshDestroy$MH = RuntimeHelper.downcallHandle(
        "NewtonMeshDestroy",
        constants$87.NewtonMeshDestroy$FUNC
    );
    public static final FunctionDescriptor NewtonMeshSerialize$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonMeshSerialize$MH = RuntimeHelper.downcallHandle(
        "NewtonMeshSerialize",
        constants$87.NewtonMeshSerialize$FUNC
    );
}


