// Generated by jextract

package crab.newton.internal;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
public final class constants$110 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$110() {}
    public static final FunctionDescriptor NewtonUserJointSetRowMassIndependentSpringDamperAcceleration$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    public static final MethodHandle NewtonUserJointSetRowMassIndependentSpringDamperAcceleration$MH = RuntimeHelper.downcallHandle(
        "NewtonUserJointSetRowMassIndependentSpringDamperAcceleration",
        constants$110.NewtonUserJointSetRowMassIndependentSpringDamperAcceleration$FUNC
    );
    public static final FunctionDescriptor NewtonUserJointSetRowStiffness$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    public static final MethodHandle NewtonUserJointSetRowStiffness$MH = RuntimeHelper.downcallHandle(
        "NewtonUserJointSetRowStiffness",
        constants$110.NewtonUserJointSetRowStiffness$FUNC
    );
    public static final FunctionDescriptor NewtonUserJoinRowsCount$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonUserJoinRowsCount$MH = RuntimeHelper.downcallHandle(
        "NewtonUserJoinRowsCount",
        constants$110.NewtonUserJoinRowsCount$FUNC
    );
    public static final FunctionDescriptor NewtonUserJointGetGeneralRow$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonUserJointGetGeneralRow$MH = RuntimeHelper.downcallHandle(
        "NewtonUserJointGetGeneralRow",
        constants$110.NewtonUserJointGetGeneralRow$FUNC
    );
    public static final FunctionDescriptor NewtonUserJointGetRowForce$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    public static final MethodHandle NewtonUserJointGetRowForce$MH = RuntimeHelper.downcallHandle(
        "NewtonUserJointGetRowForce",
        constants$110.NewtonUserJointGetRowForce$FUNC
    );
    public static final FunctionDescriptor NewtonMeshCreate$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonMeshCreate$MH = RuntimeHelper.downcallHandle(
        "NewtonMeshCreate",
        constants$110.NewtonMeshCreate$FUNC
    );
}


