// Generated by jextract
package crab.newton.internal;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
public class constants$50 {

    public static final FunctionDescriptor NewtonCreateHeightFieldCollision$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    public static final MethodHandle NewtonCreateHeightFieldCollision$MH = RuntimeHelper.downcallHandle(
        "NewtonCreateHeightFieldCollision",
        constants$50.NewtonCreateHeightFieldCollision$FUNC
    );
    public static final FunctionDescriptor NewtonHeightFieldSetUserRayCastCallback$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonHeightFieldSetUserRayCastCallback$MH = RuntimeHelper.downcallHandle(
        "NewtonHeightFieldSetUserRayCastCallback",
        constants$50.NewtonHeightFieldSetUserRayCastCallback$FUNC
    );
    public static final FunctionDescriptor NewtonCreateTreeCollision$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    public static final MethodHandle NewtonCreateTreeCollision$MH = RuntimeHelper.downcallHandle(
        "NewtonCreateTreeCollision",
        constants$50.NewtonCreateTreeCollision$FUNC
    );
    public static final FunctionDescriptor NewtonCreateTreeCollisionFromMesh$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    public static final MethodHandle NewtonCreateTreeCollisionFromMesh$MH = RuntimeHelper.downcallHandle(
        "NewtonCreateTreeCollisionFromMesh",
        constants$50.NewtonCreateTreeCollisionFromMesh$FUNC
    );
    public static final FunctionDescriptor NewtonTreeCollisionSetUserRayCastCallback$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonTreeCollisionSetUserRayCastCallback$MH = RuntimeHelper.downcallHandle(
        "NewtonTreeCollisionSetUserRayCastCallback",
        constants$50.NewtonTreeCollisionSetUserRayCastCallback$FUNC
    );
    public static final FunctionDescriptor NewtonTreeCollisionBeginBuild$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonTreeCollisionBeginBuild$MH = RuntimeHelper.downcallHandle(
        "NewtonTreeCollisionBeginBuild",
        constants$50.NewtonTreeCollisionBeginBuild$FUNC
    );
}


