// Generated by jextract

package crab.newton.internal;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
public final class constants$94 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$94() {}
    public static final FunctionDescriptor NewtonContactJointRemoveContact$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonContactJointRemoveContact$MH = RuntimeHelper.downcallHandle(
        "NewtonContactJointRemoveContact",
        constants$94.NewtonContactJointRemoveContact$FUNC
    );
    public static final FunctionDescriptor NewtonContactJointGetClosestDistance$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonContactJointGetClosestDistance$MH = RuntimeHelper.downcallHandle(
        "NewtonContactJointGetClosestDistance",
        constants$94.NewtonContactJointGetClosestDistance$FUNC
    );
    public static final FunctionDescriptor NewtonContactJointResetSelftJointCollision$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonContactJointResetSelftJointCollision$MH = RuntimeHelper.downcallHandle(
        "NewtonContactJointResetSelftJointCollision",
        constants$94.NewtonContactJointResetSelftJointCollision$FUNC
    );
    public static final FunctionDescriptor NewtonContactJointResetIntraJointCollision$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonContactJointResetIntraJointCollision$MH = RuntimeHelper.downcallHandle(
        "NewtonContactJointResetIntraJointCollision",
        constants$94.NewtonContactJointResetIntraJointCollision$FUNC
    );
    public static final FunctionDescriptor NewtonContactGetMaterial$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonContactGetMaterial$MH = RuntimeHelper.downcallHandle(
        "NewtonContactGetMaterial",
        constants$94.NewtonContactGetMaterial$FUNC
    );
    public static final FunctionDescriptor NewtonContactGetCollision0$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonContactGetCollision0$MH = RuntimeHelper.downcallHandle(
        "NewtonContactGetCollision0",
        constants$94.NewtonContactGetCollision0$FUNC
    );
}


