// Generated by jextract
package crab.newton.internal;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
public class constants$20 {

    public static final FunctionDescriptor NewtonSetPostUpdateCallback$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonSetPostUpdateCallback$MH = RuntimeHelper.downcallHandle(
        "NewtonSetPostUpdateCallback",
        constants$20.NewtonSetPostUpdateCallback$FUNC
    );
    public static final FunctionDescriptor NewtonAlloc$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    public static final MethodHandle NewtonAlloc$MH = RuntimeHelper.downcallHandle(
        "NewtonAlloc",
        constants$20.NewtonAlloc$FUNC
    );
    public static final FunctionDescriptor NewtonFree$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonFree$MH = RuntimeHelper.downcallHandle(
        "NewtonFree",
        constants$20.NewtonFree$FUNC
    );
    public static final FunctionDescriptor NewtonLoadPlugins$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonLoadPlugins$MH = RuntimeHelper.downcallHandle(
        "NewtonLoadPlugins",
        constants$20.NewtonLoadPlugins$FUNC
    );
    public static final FunctionDescriptor NewtonUnloadPlugins$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonUnloadPlugins$MH = RuntimeHelper.downcallHandle(
        "NewtonUnloadPlugins",
        constants$20.NewtonUnloadPlugins$FUNC
    );
    public static final FunctionDescriptor NewtonCurrentPlugin$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonCurrentPlugin$MH = RuntimeHelper.downcallHandle(
        "NewtonCurrentPlugin",
        constants$20.NewtonCurrentPlugin$FUNC
    );
}


