// Generated by jextract

package crab.newton.internal;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
public class constants$3 {

	public static final FunctionDescriptor NewtonWorldDestroyListenerCallback$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
	public static final MethodHandle NewtonWorldDestroyListenerCallback$MH = RuntimeHelper.downcallHandle(
        constants$3.NewtonWorldDestroyListenerCallback$FUNC, false
    );
	public static final FunctionDescriptor NewtonGetTimeInMicrosencondsCallback$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT);
	public static final MethodHandle NewtonGetTimeInMicrosencondsCallback$MH = RuntimeHelper.downcallHandle(
        constants$3.NewtonGetTimeInMicrosencondsCallback$FUNC, false
    );
	public static final FunctionDescriptor NewtonSerializeCallback$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
	public static final MethodHandle NewtonSerializeCallback$MH = RuntimeHelper.downcallHandle(
        constants$3.NewtonSerializeCallback$FUNC, false
    );
}


