// Generated by jextract

package crab.newton.internal;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
public class constants$27 {

	public static final FunctionDescriptor NewtonAtomicSwap$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
	public static final MethodHandle NewtonAtomicSwap$MH = RuntimeHelper.downcallHandle(
        "NewtonAtomicSwap",
        constants$27.NewtonAtomicSwap$FUNC, false
    );
	public static final FunctionDescriptor NewtonYield$FUNC = FunctionDescriptor.ofVoid();
	public static final MethodHandle NewtonYield$MH = RuntimeHelper.downcallHandle(
        "NewtonYield",
        constants$27.NewtonYield$FUNC, true
    );
	public static final FunctionDescriptor NewtonSetIslandUpdateEvent$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
	public static final MethodHandle NewtonSetIslandUpdateEvent$MH = RuntimeHelper.downcallHandle(
        "NewtonSetIslandUpdateEvent",
        constants$27.NewtonSetIslandUpdateEvent$FUNC, false
    );
	public static final FunctionDescriptor NewtonWorldForEachJointDo$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
	public static final MethodHandle NewtonWorldForEachJointDo$MH = RuntimeHelper.downcallHandle(
        "NewtonWorldForEachJointDo",
        constants$27.NewtonWorldForEachJointDo$FUNC, false
    );
	public static final FunctionDescriptor NewtonWorldForEachBodyInAABBDo$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
	public static final MethodHandle NewtonWorldForEachBodyInAABBDo$MH = RuntimeHelper.downcallHandle(
        "NewtonWorldForEachBodyInAABBDo",
        constants$27.NewtonWorldForEachBodyInAABBDo$FUNC, false
    );
	public static final FunctionDescriptor NewtonWorldSetUserData$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
	public static final MethodHandle NewtonWorldSetUserData$MH = RuntimeHelper.downcallHandle(
        "NewtonWorldSetUserData",
        constants$27.NewtonWorldSetUserData$FUNC, false
    );
}


