// Generated by jextract

package crab.newton.internal;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
public class constants$49 {

	public static final FunctionDescriptor NewtonSceneCollisionGetCollisionFromNode$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
	public static final MethodHandle NewtonSceneCollisionGetCollisionFromNode$MH = RuntimeHelper.downcallHandle(
        "NewtonSceneCollisionGetCollisionFromNode",
        constants$49.NewtonSceneCollisionGetCollisionFromNode$FUNC, false
    );
	public static final FunctionDescriptor NewtonCreateUserMeshCollision$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
	public static final MethodHandle NewtonCreateUserMeshCollision$MH = RuntimeHelper.downcallHandle(
        "NewtonCreateUserMeshCollision",
        constants$49.NewtonCreateUserMeshCollision$FUNC, false
    );
	public static final FunctionDescriptor NewtonUserMeshCollisionContinuousOverlapTest$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
	public static final MethodHandle NewtonUserMeshCollisionContinuousOverlapTest$MH = RuntimeHelper.downcallHandle(
        "NewtonUserMeshCollisionContinuousOverlapTest",
        constants$49.NewtonUserMeshCollisionContinuousOverlapTest$FUNC, false
    );
	public static final FunctionDescriptor NewtonCreateCollisionFromSerialization$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
	public static final MethodHandle NewtonCreateCollisionFromSerialization$MH = RuntimeHelper.downcallHandle(
        "NewtonCreateCollisionFromSerialization",
        constants$49.NewtonCreateCollisionFromSerialization$FUNC, false
    );
	public static final FunctionDescriptor NewtonCollisionSerialize$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
	public static final MethodHandle NewtonCollisionSerialize$MH = RuntimeHelper.downcallHandle(
        "NewtonCollisionSerialize",
        constants$49.NewtonCollisionSerialize$FUNC, false
    );
	public static final FunctionDescriptor NewtonCollisionGetInfo$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
	public static final MethodHandle NewtonCollisionGetInfo$MH = RuntimeHelper.downcallHandle(
        "NewtonCollisionGetInfo",
        constants$49.NewtonCollisionGetInfo$FUNC, false
    );
}


