// Generated by jextract

package crab.newton.internal;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
public final class constants$56 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$56() {}
    public static final FunctionDescriptor NewtonCompoundCollisionRemoveSubCollisionByIndex$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    public static final MethodHandle NewtonCompoundCollisionRemoveSubCollisionByIndex$MH = RuntimeHelper.downcallHandle(
        "NewtonCompoundCollisionRemoveSubCollisionByIndex",
        constants$56.NewtonCompoundCollisionRemoveSubCollisionByIndex$FUNC
    );
    public static final FunctionDescriptor NewtonCompoundCollisionSetSubCollisionMatrix$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonCompoundCollisionSetSubCollisionMatrix$MH = RuntimeHelper.downcallHandle(
        "NewtonCompoundCollisionSetSubCollisionMatrix",
        constants$56.NewtonCompoundCollisionSetSubCollisionMatrix$FUNC
    );
    public static final FunctionDescriptor NewtonCompoundCollisionEndAddRemove$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonCompoundCollisionEndAddRemove$MH = RuntimeHelper.downcallHandle(
        "NewtonCompoundCollisionEndAddRemove",
        constants$56.NewtonCompoundCollisionEndAddRemove$FUNC
    );
    public static final FunctionDescriptor NewtonCompoundCollisionGetFirstNode$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonCompoundCollisionGetFirstNode$MH = RuntimeHelper.downcallHandle(
        "NewtonCompoundCollisionGetFirstNode",
        constants$56.NewtonCompoundCollisionGetFirstNode$FUNC
    );
    public static final FunctionDescriptor NewtonCompoundCollisionGetNextNode$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonCompoundCollisionGetNextNode$MH = RuntimeHelper.downcallHandle(
        "NewtonCompoundCollisionGetNextNode",
        constants$56.NewtonCompoundCollisionGetNextNode$FUNC
    );
    public static final FunctionDescriptor NewtonCompoundCollisionGetNodeByIndex$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    public static final MethodHandle NewtonCompoundCollisionGetNodeByIndex$MH = RuntimeHelper.downcallHandle(
        "NewtonCompoundCollisionGetNodeByIndex",
        constants$56.NewtonCompoundCollisionGetNodeByIndex$FUNC
    );
}


