// Generated by jextract

package crab.newton.internal;

import java.lang.invoke.MethodHandle;
import java.lang.foreign.*;
import crab.newton.callbacks.*;
public final class constants$41 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$41() {}
    public static final FunctionDescriptor NewtonWorldRayCast$filter$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    public static final FunctionDescriptor NewtonWorldRayCast$filter_UP$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    public static final MethodHandle NewtonWorldRayCast$filter_UP$MH = RuntimeHelper.upcallHandle(NewtonWorldRayCast$filter.class, "apply", constants$41.NewtonWorldRayCast$filter_UP$FUNC);
    public static final FunctionDescriptor NewtonWorldRayCast$filter_DOWN$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    public static final MethodHandle NewtonWorldRayCast$filter_DOWN$MH = RuntimeHelper.downcallHandle(
        constants$41.NewtonWorldRayCast$filter_DOWN$FUNC
    );
    public static final FunctionDescriptor NewtonWorldRayCast$prefilter$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final FunctionDescriptor NewtonWorldRayCast$prefilter_UP$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonWorldRayCast$prefilter_UP$MH = RuntimeHelper.upcallHandle(NewtonWorldRayCast$prefilter.class, "apply", constants$41.NewtonWorldRayCast$prefilter_UP$FUNC);
    public static final FunctionDescriptor NewtonWorldRayCast$prefilter_DOWN$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonWorldRayCast$prefilter_DOWN$MH = RuntimeHelper.downcallHandle(
        constants$41.NewtonWorldRayCast$prefilter_DOWN$FUNC
    );
    public static final FunctionDescriptor NewtonWorldRayCast$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    public static final MethodHandle NewtonWorldRayCast$MH = RuntimeHelper.downcallHandle(
        "NewtonWorldRayCast",
        constants$41.NewtonWorldRayCast$FUNC
    );
    public static final FunctionDescriptor NewtonWorldConvexCast$prefilter$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final FunctionDescriptor NewtonWorldConvexCast$prefilter_UP$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonWorldConvexCast$prefilter_UP$MH = RuntimeHelper.upcallHandle(NewtonWorldConvexCast$prefilter.class, "apply", constants$41.NewtonWorldConvexCast$prefilter_UP$FUNC);
}


