// Generated by jextract

package crab.newton.internal;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
public final class constants$90 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$90() {}
    public static final FunctionDescriptor NewtonBodyGetInvInertiaMatrix$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonBodyGetInvInertiaMatrix$MH = RuntimeHelper.downcallHandle(
        "NewtonBodyGetInvInertiaMatrix",
        constants$90.NewtonBodyGetInvInertiaMatrix$FUNC
    );
    public static final FunctionDescriptor NewtonBodyGetOmega$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonBodyGetOmega$MH = RuntimeHelper.downcallHandle(
        "NewtonBodyGetOmega",
        constants$90.NewtonBodyGetOmega$FUNC
    );
    public static final FunctionDescriptor NewtonBodyGetVelocity$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonBodyGetVelocity$MH = RuntimeHelper.downcallHandle(
        "NewtonBodyGetVelocity",
        constants$90.NewtonBodyGetVelocity$FUNC
    );
    public static final FunctionDescriptor NewtonBodyGetAlpha$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonBodyGetAlpha$MH = RuntimeHelper.downcallHandle(
        "NewtonBodyGetAlpha",
        constants$90.NewtonBodyGetAlpha$FUNC
    );
    public static final FunctionDescriptor NewtonBodyGetAcceleration$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonBodyGetAcceleration$MH = RuntimeHelper.downcallHandle(
        "NewtonBodyGetAcceleration",
        constants$90.NewtonBodyGetAcceleration$FUNC
    );
    public static final FunctionDescriptor NewtonBodyGetForce$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonBodyGetForce$MH = RuntimeHelper.downcallHandle(
        "NewtonBodyGetForce",
        constants$90.NewtonBodyGetForce$FUNC
    );
}


