// Generated by jextract

package crab.newton.internal;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import crab.newton.callbacks.*;
public final class constants$33 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$33() {}
    public static final FunctionDescriptor NewtonWorldForEachJointDo$callback_DOWN$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonWorldForEachJointDo$callback_DOWN$MH = RuntimeHelper.downcallHandle(
        constants$33.NewtonWorldForEachJointDo$callback_DOWN$FUNC
    );
    public static final FunctionDescriptor NewtonWorldForEachJointDo$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonWorldForEachJointDo$MH = RuntimeHelper.downcallHandle(
        "NewtonWorldForEachJointDo",
        constants$33.NewtonWorldForEachJointDo$FUNC
    );
    public static final FunctionDescriptor NewtonWorldForEachBodyInAABBDo$callback$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final FunctionDescriptor NewtonWorldForEachBodyInAABBDo$callback_UP$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonWorldForEachBodyInAABBDo$callback_UP$MH = RuntimeHelper.upcallHandle(NewtonWorldForEachBodyInAABBDo$callback.class, "apply", constants$33.NewtonWorldForEachBodyInAABBDo$callback_UP$FUNC);
    public static final FunctionDescriptor NewtonWorldForEachBodyInAABBDo$callback_DOWN$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonWorldForEachBodyInAABBDo$callback_DOWN$MH = RuntimeHelper.downcallHandle(
        constants$33.NewtonWorldForEachBodyInAABBDo$callback_DOWN$FUNC
    );
    public static final FunctionDescriptor NewtonWorldForEachBodyInAABBDo$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonWorldForEachBodyInAABBDo$MH = RuntimeHelper.downcallHandle(
        "NewtonWorldForEachBodyInAABBDo",
        constants$33.NewtonWorldForEachBodyInAABBDo$FUNC
    );
    public static final FunctionDescriptor NewtonWorldSetUserData$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonWorldSetUserData$MH = RuntimeHelper.downcallHandle(
        "NewtonWorldSetUserData",
        constants$33.NewtonWorldSetUserData$FUNC
    );
}


