// Generated by jextract

package crab.newton.internal;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
public final class constants$53 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$53() {}
    public static final FunctionDescriptor NewtonCreateCapsule$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonCreateCapsule$MH = RuntimeHelper.downcallHandle(
        "NewtonCreateCapsule",
        constants$53.NewtonCreateCapsule$FUNC
    );
    public static final FunctionDescriptor NewtonCreateCylinder$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonCreateCylinder$MH = RuntimeHelper.downcallHandle(
        "NewtonCreateCylinder",
        constants$53.NewtonCreateCylinder$FUNC
    );
    public static final FunctionDescriptor NewtonCreateChamferCylinder$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonCreateChamferCylinder$MH = RuntimeHelper.downcallHandle(
        "NewtonCreateChamferCylinder",
        constants$53.NewtonCreateChamferCylinder$FUNC
    );
    public static final FunctionDescriptor NewtonCreateConvexHull$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonCreateConvexHull$MH = RuntimeHelper.downcallHandle(
        "NewtonCreateConvexHull",
        constants$53.NewtonCreateConvexHull$FUNC
    );
    public static final FunctionDescriptor NewtonCreateConvexHullFromMesh$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    public static final MethodHandle NewtonCreateConvexHullFromMesh$MH = RuntimeHelper.downcallHandle(
        "NewtonCreateConvexHullFromMesh",
        constants$53.NewtonCreateConvexHullFromMesh$FUNC
    );
    public static final FunctionDescriptor NewtonCollisionGetMode$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonCollisionGetMode$MH = RuntimeHelper.downcallHandle(
        "NewtonCollisionGetMode",
        constants$53.NewtonCollisionGetMode$FUNC
    );
}


