// Generated by jextract
package crab.newton.internal;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
public class constants$100 {

    public static final FunctionDescriptor NewtonMeshGetVertexArray$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonMeshGetVertexArray$MH = RuntimeHelper.downcallHandle(
        "NewtonMeshGetVertexArray",
        constants$100.NewtonMeshGetVertexArray$FUNC
    );
    public static final FunctionDescriptor NewtonMeshGetVertexBaseCount$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonMeshGetVertexBaseCount$MH = RuntimeHelper.downcallHandle(
        "NewtonMeshGetVertexBaseCount",
        constants$100.NewtonMeshGetVertexBaseCount$FUNC
    );
    public static final FunctionDescriptor NewtonMeshSetVertexBaseCount$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    public static final MethodHandle NewtonMeshSetVertexBaseCount$MH = RuntimeHelper.downcallHandle(
        "NewtonMeshSetVertexBaseCount",
        constants$100.NewtonMeshSetVertexBaseCount$FUNC
    );
    public static final FunctionDescriptor NewtonMeshGetFirstVertex$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonMeshGetFirstVertex$MH = RuntimeHelper.downcallHandle(
        "NewtonMeshGetFirstVertex",
        constants$100.NewtonMeshGetFirstVertex$FUNC
    );
    public static final FunctionDescriptor NewtonMeshGetNextVertex$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonMeshGetNextVertex$MH = RuntimeHelper.downcallHandle(
        "NewtonMeshGetNextVertex",
        constants$100.NewtonMeshGetNextVertex$FUNC
    );
    public static final FunctionDescriptor NewtonMeshGetVertexIndex$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonMeshGetVertexIndex$MH = RuntimeHelper.downcallHandle(
        "NewtonMeshGetVertexIndex",
        constants$100.NewtonMeshGetVertexIndex$FUNC
    );
}


