// Generated by jextract

package crab.newton.internal;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
public final class constants$108 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$108() {}
    public static final FunctionDescriptor NewtonUserJointSetFeedbackCollectorCallback$getFeedback_DOWN$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    public static final MethodHandle NewtonUserJointSetFeedbackCollectorCallback$getFeedback_DOWN$MH = RuntimeHelper.downcallHandle(
        constants$108.NewtonUserJointSetFeedbackCollectorCallback$getFeedback_DOWN$FUNC
    );
    public static final FunctionDescriptor NewtonUserJointSetFeedbackCollectorCallback$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonUserJointSetFeedbackCollectorCallback$MH = RuntimeHelper.downcallHandle(
        "NewtonUserJointSetFeedbackCollectorCallback",
        constants$108.NewtonUserJointSetFeedbackCollectorCallback$FUNC
    );
    public static final FunctionDescriptor NewtonUserJointAddLinearRow$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonUserJointAddLinearRow$MH = RuntimeHelper.downcallHandle(
        "NewtonUserJointAddLinearRow",
        constants$108.NewtonUserJointAddLinearRow$FUNC
    );
    public static final FunctionDescriptor NewtonUserJointAddAngularRow$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonUserJointAddAngularRow$MH = RuntimeHelper.downcallHandle(
        "NewtonUserJointAddAngularRow",
        constants$108.NewtonUserJointAddAngularRow$FUNC
    );
    public static final FunctionDescriptor NewtonUserJointAddGeneralRow$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonUserJointAddGeneralRow$MH = RuntimeHelper.downcallHandle(
        "NewtonUserJointAddGeneralRow",
        constants$108.NewtonUserJointAddGeneralRow$FUNC
    );
    public static final FunctionDescriptor NewtonUserJointSetRowMinimumFriction$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    public static final MethodHandle NewtonUserJointSetRowMinimumFriction$MH = RuntimeHelper.downcallHandle(
        "NewtonUserJointSetRowMinimumFriction",
        constants$108.NewtonUserJointSetRowMinimumFriction$FUNC
    );
}


