// Generated by jextract

package crab.newton.internal;

import java.lang.invoke.MethodHandle;
import java.lang.foreign.*;
import crab.newton.callbacks.*;
public final class constants$71 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$71() {}
    public static final FunctionDescriptor NewtonStaticCollisionSetDebugCallback$userCallback$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    public static final FunctionDescriptor NewtonStaticCollisionSetDebugCallback$userCallback_UP$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    public static final MethodHandle NewtonStaticCollisionSetDebugCallback$userCallback_UP$MH = RuntimeHelper.upcallHandle(NewtonStaticCollisionSetDebugCallback$userCallback.class, "apply", constants$71.NewtonStaticCollisionSetDebugCallback$userCallback_UP$FUNC);
    public static final FunctionDescriptor NewtonStaticCollisionSetDebugCallback$userCallback_DOWN$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    public static final MethodHandle NewtonStaticCollisionSetDebugCallback$userCallback_DOWN$MH = RuntimeHelper.downcallHandle(
        constants$71.NewtonStaticCollisionSetDebugCallback$userCallback_DOWN$FUNC
    );
    public static final FunctionDescriptor NewtonStaticCollisionSetDebugCallback$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonStaticCollisionSetDebugCallback$MH = RuntimeHelper.downcallHandle(
        "NewtonStaticCollisionSetDebugCallback",
        constants$71.NewtonStaticCollisionSetDebugCallback$FUNC
    );
    public static final FunctionDescriptor NewtonCollisionCreateInstance$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonCollisionCreateInstance$MH = RuntimeHelper.downcallHandle(
        "NewtonCollisionCreateInstance",
        constants$71.NewtonCollisionCreateInstance$FUNC
    );
    public static final FunctionDescriptor NewtonCollisionGetType$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonCollisionGetType$MH = RuntimeHelper.downcallHandle(
        "NewtonCollisionGetType",
        constants$71.NewtonCollisionGetType$FUNC
    );
    public static final FunctionDescriptor NewtonCollisionIsConvexShape$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonCollisionIsConvexShape$MH = RuntimeHelper.downcallHandle(
        "NewtonCollisionIsConvexShape",
        constants$71.NewtonCollisionIsConvexShape$FUNC
    );
}


