// Generated by jextract

package crab.newton.internal;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
public class constants$18 {

	public static final FunctionDescriptor NewtonJobTask$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
	public static final MethodHandle NewtonJobTask$MH = RuntimeHelper.downcallHandle(
        constants$18.NewtonJobTask$FUNC, false
    );
	public static final FunctionDescriptor NewtonReportProgress$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
	public static final MethodHandle NewtonReportProgress$MH = RuntimeHelper.downcallHandle(
        constants$18.NewtonReportProgress$FUNC, false
    );
	public static final FunctionDescriptor NewtonWorldGetVersion$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT);
	public static final MethodHandle NewtonWorldGetVersion$MH = RuntimeHelper.downcallHandle(
        "NewtonWorldGetVersion",
        constants$18.NewtonWorldGetVersion$FUNC, true
    );
	public static final FunctionDescriptor NewtonWorldFloatSize$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT);
	public static final MethodHandle NewtonWorldFloatSize$MH = RuntimeHelper.downcallHandle(
        "NewtonWorldFloatSize",
        constants$18.NewtonWorldFloatSize$FUNC, true
    );
}


