// Generated by jextract
package crab.newton.internal;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
public class constants$34 {

    public static final FunctionDescriptor NewtonMaterialSetDefaultFriction$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    public static final MethodHandle NewtonMaterialSetDefaultFriction$MH = RuntimeHelper.downcallHandle(
        "NewtonMaterialSetDefaultFriction",
        constants$34.NewtonMaterialSetDefaultFriction$FUNC
    );
    public static final FunctionDescriptor NewtonMaterialJointResetIntraJointCollision$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    public static final MethodHandle NewtonMaterialJointResetIntraJointCollision$MH = RuntimeHelper.downcallHandle(
        "NewtonMaterialJointResetIntraJointCollision",
        constants$34.NewtonMaterialJointResetIntraJointCollision$FUNC
    );
    public static final FunctionDescriptor NewtonMaterialJointResetSelftJointCollision$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    public static final MethodHandle NewtonMaterialJointResetSelftJointCollision$MH = RuntimeHelper.downcallHandle(
        "NewtonMaterialJointResetSelftJointCollision",
        constants$34.NewtonMaterialJointResetSelftJointCollision$FUNC
    );
    public static final FunctionDescriptor NewtonWorldGetFirstMaterial$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonWorldGetFirstMaterial$MH = RuntimeHelper.downcallHandle(
        "NewtonWorldGetFirstMaterial",
        constants$34.NewtonWorldGetFirstMaterial$FUNC
    );
    public static final FunctionDescriptor NewtonWorldGetNextMaterial$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonWorldGetNextMaterial$MH = RuntimeHelper.downcallHandle(
        "NewtonWorldGetNextMaterial",
        constants$34.NewtonWorldGetNextMaterial$FUNC
    );
    public static final FunctionDescriptor NewtonWorldGetFirstBody$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonWorldGetFirstBody$MH = RuntimeHelper.downcallHandle(
        "NewtonWorldGetFirstBody",
        constants$34.NewtonWorldGetFirstBody$FUNC
    );
}


