// Generated by jextract

package crab.newton.internal;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
public final class constants$83 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$83() {}
    public static final FunctionDescriptor NewtonBodySetCollisionScale$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    public static final MethodHandle NewtonBodySetCollisionScale$MH = RuntimeHelper.downcallHandle(
        "NewtonBodySetCollisionScale",
        constants$83.NewtonBodySetCollisionScale$FUNC
    );
    public static final FunctionDescriptor NewtonBodyGetSleepState$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonBodyGetSleepState$MH = RuntimeHelper.downcallHandle(
        "NewtonBodyGetSleepState",
        constants$83.NewtonBodyGetSleepState$FUNC
    );
    public static final FunctionDescriptor NewtonBodySetSleepState$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    public static final MethodHandle NewtonBodySetSleepState$MH = RuntimeHelper.downcallHandle(
        "NewtonBodySetSleepState",
        constants$83.NewtonBodySetSleepState$FUNC
    );
    public static final FunctionDescriptor NewtonBodyGetAutoSleep$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonBodyGetAutoSleep$MH = RuntimeHelper.downcallHandle(
        "NewtonBodyGetAutoSleep",
        constants$83.NewtonBodyGetAutoSleep$FUNC
    );
    public static final FunctionDescriptor NewtonBodySetAutoSleep$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    public static final MethodHandle NewtonBodySetAutoSleep$MH = RuntimeHelper.downcallHandle(
        "NewtonBodySetAutoSleep",
        constants$83.NewtonBodySetAutoSleep$FUNC
    );
    public static final FunctionDescriptor NewtonBodyGetFreezeState$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonBodyGetFreezeState$MH = RuntimeHelper.downcallHandle(
        "NewtonBodyGetFreezeState",
        constants$83.NewtonBodyGetFreezeState$FUNC
    );
}


