// Generated by jextract
package crab.newton.internal;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
public class constants$48 {

    public static final FunctionDescriptor NewtonSceneCollisionSetSubCollisionMatrix$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonSceneCollisionSetSubCollisionMatrix$MH = RuntimeHelper.downcallHandle(
        "NewtonSceneCollisionSetSubCollisionMatrix",
        constants$48.NewtonSceneCollisionSetSubCollisionMatrix$FUNC
    );
    public static final FunctionDescriptor NewtonSceneCollisionEndAddRemove$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonSceneCollisionEndAddRemove$MH = RuntimeHelper.downcallHandle(
        "NewtonSceneCollisionEndAddRemove",
        constants$48.NewtonSceneCollisionEndAddRemove$FUNC
    );
    public static final FunctionDescriptor NewtonSceneCollisionGetFirstNode$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonSceneCollisionGetFirstNode$MH = RuntimeHelper.downcallHandle(
        "NewtonSceneCollisionGetFirstNode",
        constants$48.NewtonSceneCollisionGetFirstNode$FUNC
    );
    public static final FunctionDescriptor NewtonSceneCollisionGetNextNode$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonSceneCollisionGetNextNode$MH = RuntimeHelper.downcallHandle(
        "NewtonSceneCollisionGetNextNode",
        constants$48.NewtonSceneCollisionGetNextNode$FUNC
    );
    public static final FunctionDescriptor NewtonSceneCollisionGetNodeByIndex$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    public static final MethodHandle NewtonSceneCollisionGetNodeByIndex$MH = RuntimeHelper.downcallHandle(
        "NewtonSceneCollisionGetNodeByIndex",
        constants$48.NewtonSceneCollisionGetNodeByIndex$FUNC
    );
    public static final FunctionDescriptor NewtonSceneCollisionGetNodeIndex$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonSceneCollisionGetNodeIndex$MH = RuntimeHelper.downcallHandle(
        "NewtonSceneCollisionGetNodeIndex",
        constants$48.NewtonSceneCollisionGetNodeIndex$FUNC
    );
}


