// Generated by jextract

package crab.newton.internal;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
public class constants$89 {

	public static final FunctionDescriptor NewtonMeshCalculateVertexNormals$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
	public static final MethodHandle NewtonMeshCalculateVertexNormals$MH = RuntimeHelper.downcallHandle(
        "NewtonMeshCalculateVertexNormals",
        constants$89.NewtonMeshCalculateVertexNormals$FUNC, false
    );
	public static final FunctionDescriptor NewtonMeshApplySphericalMapping$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
	public static final MethodHandle NewtonMeshApplySphericalMapping$MH = RuntimeHelper.downcallHandle(
        "NewtonMeshApplySphericalMapping",
        constants$89.NewtonMeshApplySphericalMapping$FUNC, false
    );
	public static final FunctionDescriptor NewtonMeshApplyCylindricalMapping$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
	public static final MethodHandle NewtonMeshApplyCylindricalMapping$MH = RuntimeHelper.downcallHandle(
        "NewtonMeshApplyCylindricalMapping",
        constants$89.NewtonMeshApplyCylindricalMapping$FUNC, false
    );
	public static final FunctionDescriptor NewtonMeshApplyBoxMapping$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
	public static final MethodHandle NewtonMeshApplyBoxMapping$MH = RuntimeHelper.downcallHandle(
        "NewtonMeshApplyBoxMapping",
        constants$89.NewtonMeshApplyBoxMapping$FUNC, false
    );
	public static final FunctionDescriptor NewtonMeshApplyAngleBasedMapping$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
	public static final MethodHandle NewtonMeshApplyAngleBasedMapping$MH = RuntimeHelper.downcallHandle(
        "NewtonMeshApplyAngleBasedMapping",
        constants$89.NewtonMeshApplyAngleBasedMapping$FUNC, false
    );
	public static final FunctionDescriptor NewtonCreateTetrahedraLinearBlendSkinWeightsChannel$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
	public static final MethodHandle NewtonCreateTetrahedraLinearBlendSkinWeightsChannel$MH = RuntimeHelper.downcallHandle(
        "NewtonCreateTetrahedraLinearBlendSkinWeightsChannel",
        constants$89.NewtonCreateTetrahedraLinearBlendSkinWeightsChannel$FUNC, false
    );
}


