// Generated by jextract

package crab.newton.internal;

import java.lang.invoke.MethodHandle;
import java.lang.foreign.*;
import crab.newton.callbacks.*;
public final class constants$65 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$65() {}
    public static final FunctionDescriptor NewtonCreateUserMeshCollision$destroyCallback_DOWN$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonCreateUserMeshCollision$destroyCallback_DOWN$MH = RuntimeHelper.downcallHandle(
        constants$65.NewtonCreateUserMeshCollision$destroyCallback_DOWN$FUNC
    );
    public static final FunctionDescriptor NewtonCreateUserMeshCollision$getInfoCallback$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final FunctionDescriptor NewtonCreateUserMeshCollision$getInfoCallback_UP$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonCreateUserMeshCollision$getInfoCallback_UP$MH = RuntimeHelper.upcallHandle(NewtonCreateUserMeshCollision$getInfoCallback.class, "apply", constants$65.NewtonCreateUserMeshCollision$getInfoCallback_UP$FUNC);
    public static final FunctionDescriptor NewtonCreateUserMeshCollision$getInfoCallback_DOWN$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonCreateUserMeshCollision$getInfoCallback_DOWN$MH = RuntimeHelper.downcallHandle(
        constants$65.NewtonCreateUserMeshCollision$getInfoCallback_DOWN$FUNC
    );
    public static final FunctionDescriptor NewtonCreateUserMeshCollision$getLocalAABBCallback$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final FunctionDescriptor NewtonCreateUserMeshCollision$getLocalAABBCallback_UP$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonCreateUserMeshCollision$getLocalAABBCallback_UP$MH = RuntimeHelper.upcallHandle(NewtonCreateUserMeshCollision$getLocalAABBCallback.class, "apply", constants$65.NewtonCreateUserMeshCollision$getLocalAABBCallback_UP$FUNC);
    public static final FunctionDescriptor NewtonCreateUserMeshCollision$getLocalAABBCallback_DOWN$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonCreateUserMeshCollision$getLocalAABBCallback_DOWN$MH = RuntimeHelper.downcallHandle(
        constants$65.NewtonCreateUserMeshCollision$getLocalAABBCallback_DOWN$FUNC
    );
    public static final FunctionDescriptor NewtonCreateUserMeshCollision$facesInAABBCallback$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final FunctionDescriptor NewtonCreateUserMeshCollision$facesInAABBCallback_UP$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonCreateUserMeshCollision$facesInAABBCallback_UP$MH = RuntimeHelper.upcallHandle(NewtonCreateUserMeshCollision$facesInAABBCallback.class, "apply", constants$65.NewtonCreateUserMeshCollision$facesInAABBCallback_UP$FUNC);
}


