// Generated by jextract
package crab.newton.internal;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
public class constants$62 {

    public static final FunctionDescriptor NewtonBodySetOmegaNoSleep$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonBodySetOmegaNoSleep$MH = RuntimeHelper.downcallHandle(
        "NewtonBodySetOmegaNoSleep",
        constants$62.NewtonBodySetOmegaNoSleep$FUNC
    );
    public static final FunctionDescriptor NewtonBodySetVelocity$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonBodySetVelocity$MH = RuntimeHelper.downcallHandle(
        "NewtonBodySetVelocity",
        constants$62.NewtonBodySetVelocity$FUNC
    );
    public static final FunctionDescriptor NewtonBodySetVelocityNoSleep$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonBodySetVelocityNoSleep$MH = RuntimeHelper.downcallHandle(
        "NewtonBodySetVelocityNoSleep",
        constants$62.NewtonBodySetVelocityNoSleep$FUNC
    );
    public static final FunctionDescriptor NewtonBodySetForce$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonBodySetForce$MH = RuntimeHelper.downcallHandle(
        "NewtonBodySetForce",
        constants$62.NewtonBodySetForce$FUNC
    );
    public static final FunctionDescriptor NewtonBodySetTorque$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonBodySetTorque$MH = RuntimeHelper.downcallHandle(
        "NewtonBodySetTorque",
        constants$62.NewtonBodySetTorque$FUNC
    );
    public static final FunctionDescriptor NewtonBodySetLinearDamping$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    public static final MethodHandle NewtonBodySetLinearDamping$MH = RuntimeHelper.downcallHandle(
        "NewtonBodySetLinearDamping",
        constants$62.NewtonBodySetLinearDamping$FUNC
    );
}


