// Generated by jextract

package crab.newton.internal;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
public final class constants$50 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$50() {}
    public static final FunctionDescriptor NewtonMaterialSetAsSoftContact$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    public static final MethodHandle NewtonMaterialSetAsSoftContact$MH = RuntimeHelper.downcallHandle(
        "NewtonMaterialSetAsSoftContact",
        constants$50.NewtonMaterialSetAsSoftContact$FUNC
    );
    public static final FunctionDescriptor NewtonMaterialSetContactSoftness$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    public static final MethodHandle NewtonMaterialSetContactSoftness$MH = RuntimeHelper.downcallHandle(
        "NewtonMaterialSetContactSoftness",
        constants$50.NewtonMaterialSetContactSoftness$FUNC
    );
    public static final FunctionDescriptor NewtonMaterialSetContactThickness$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    public static final MethodHandle NewtonMaterialSetContactThickness$MH = RuntimeHelper.downcallHandle(
        "NewtonMaterialSetContactThickness",
        constants$50.NewtonMaterialSetContactThickness$FUNC
    );
    public static final FunctionDescriptor NewtonMaterialSetContactElasticity$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    public static final MethodHandle NewtonMaterialSetContactElasticity$MH = RuntimeHelper.downcallHandle(
        "NewtonMaterialSetContactElasticity",
        constants$50.NewtonMaterialSetContactElasticity$FUNC
    );
    public static final FunctionDescriptor NewtonMaterialSetContactFrictionState$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    public static final MethodHandle NewtonMaterialSetContactFrictionState$MH = RuntimeHelper.downcallHandle(
        "NewtonMaterialSetContactFrictionState",
        constants$50.NewtonMaterialSetContactFrictionState$FUNC
    );
    public static final FunctionDescriptor NewtonMaterialSetContactFrictionCoef$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    public static final MethodHandle NewtonMaterialSetContactFrictionCoef$MH = RuntimeHelper.downcallHandle(
        "NewtonMaterialSetContactFrictionCoef",
        constants$50.NewtonMaterialSetContactFrictionCoef$FUNC
    );
}


