// Generated by jextract
package crab.newton.internal;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
public class constants$25 {

    public static final FunctionDescriptor NewtonDeserializeScene$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonDeserializeScene$MH = RuntimeHelper.downcallHandle(
        "NewtonDeserializeScene",
        constants$25.NewtonDeserializeScene$FUNC
    );
    public static final FunctionDescriptor NewtonFindSerializedBody$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    public static final MethodHandle NewtonFindSerializedBody$MH = RuntimeHelper.downcallHandle(
        "NewtonFindSerializedBody",
        constants$25.NewtonFindSerializedBody$FUNC
    );
    public static final FunctionDescriptor NewtonSetJointSerializationCallbacks$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonSetJointSerializationCallbacks$MH = RuntimeHelper.downcallHandle(
        "NewtonSetJointSerializationCallbacks",
        constants$25.NewtonSetJointSerializationCallbacks$FUNC
    );
    public static final FunctionDescriptor NewtonGetJointSerializationCallbacks$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonGetJointSerializationCallbacks$MH = RuntimeHelper.downcallHandle(
        "NewtonGetJointSerializationCallbacks",
        constants$25.NewtonGetJointSerializationCallbacks$FUNC
    );
    public static final FunctionDescriptor NewtonWorldCriticalSectionLock$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    public static final MethodHandle NewtonWorldCriticalSectionLock$MH = RuntimeHelper.downcallHandle(
        "NewtonWorldCriticalSectionLock",
        constants$25.NewtonWorldCriticalSectionLock$FUNC
    );
    public static final FunctionDescriptor NewtonWorldCriticalSectionUnlock$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonWorldCriticalSectionUnlock$MH = RuntimeHelper.downcallHandle(
        "NewtonWorldCriticalSectionUnlock",
        constants$25.NewtonWorldCriticalSectionUnlock$FUNC
    );
}


