// Generated by jextract

package crab.newton.internal;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
public class constants$30 {

	public static final FunctionDescriptor NewtonWorldSetDestructorCallback$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
	public static final MethodHandle NewtonWorldSetDestructorCallback$MH = RuntimeHelper.downcallHandle(
        "NewtonWorldSetDestructorCallback",
        constants$30.NewtonWorldSetDestructorCallback$FUNC, false
    );
	public static final FunctionDescriptor NewtonWorldGetDestructorCallback$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
	public static final MethodHandle NewtonWorldGetDestructorCallback$MH = RuntimeHelper.downcallHandle(
        "NewtonWorldGetDestructorCallback",
        constants$30.NewtonWorldGetDestructorCallback$FUNC, false
    );
	public static final FunctionDescriptor NewtonWorldSetCollisionConstructorDestructorCallback$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
	public static final MethodHandle NewtonWorldSetCollisionConstructorDestructorCallback$MH = RuntimeHelper.downcallHandle(
        "NewtonWorldSetCollisionConstructorDestructorCallback",
        constants$30.NewtonWorldSetCollisionConstructorDestructorCallback$FUNC, false
    );
	public static final FunctionDescriptor NewtonWorldSetCreateDestroyContactCallback$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
	public static final MethodHandle NewtonWorldSetCreateDestroyContactCallback$MH = RuntimeHelper.downcallHandle(
        "NewtonWorldSetCreateDestroyContactCallback",
        constants$30.NewtonWorldSetCreateDestroyContactCallback$FUNC, false
    );
	public static final FunctionDescriptor NewtonWorldRayCast$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
	public static final MethodHandle NewtonWorldRayCast$MH = RuntimeHelper.downcallHandle(
        "NewtonWorldRayCast",
        constants$30.NewtonWorldRayCast$FUNC, false
    );
	public static final FunctionDescriptor NewtonWorldConvexCast$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
	public static final MethodHandle NewtonWorldConvexCast$MH = RuntimeHelper.downcallHandle(
        "NewtonWorldConvexCast",
        constants$30.NewtonWorldConvexCast$FUNC, false
    );
}


