// Generated by jextract

package crab.newton.internal;

import java.lang.invoke.MethodHandle;
import java.lang.foreign.*;
import crab.newton.callbacks.*;
public final class constants$40 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$40() {}
    public static final FunctionDescriptor NewtonWorldSetCollisionConstructorDestructorCallback$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonWorldSetCollisionConstructorDestructorCallback$MH = RuntimeHelper.downcallHandle(
        "NewtonWorldSetCollisionConstructorDestructorCallback",
        constants$40.NewtonWorldSetCollisionConstructorDestructorCallback$FUNC
    );
    public static final FunctionDescriptor NewtonWorldSetCreateDestroyContactCallback$createContact$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final FunctionDescriptor NewtonWorldSetCreateDestroyContactCallback$createContact_UP$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonWorldSetCreateDestroyContactCallback$createContact_UP$MH = RuntimeHelper.upcallHandle(NewtonWorldSetCreateDestroyContactCallback$createContact.class, "apply", constants$40.NewtonWorldSetCreateDestroyContactCallback$createContact_UP$FUNC);
    public static final FunctionDescriptor NewtonWorldSetCreateDestroyContactCallback$createContact_DOWN$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonWorldSetCreateDestroyContactCallback$createContact_DOWN$MH = RuntimeHelper.downcallHandle(
        constants$40.NewtonWorldSetCreateDestroyContactCallback$createContact_DOWN$FUNC
    );
    public static final FunctionDescriptor NewtonWorldSetCreateDestroyContactCallback$destroyContact$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final FunctionDescriptor NewtonWorldSetCreateDestroyContactCallback$destroyContact_UP$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonWorldSetCreateDestroyContactCallback$destroyContact_UP$MH = RuntimeHelper.upcallHandle(NewtonWorldSetCreateDestroyContactCallback$destroyContact.class, "apply", constants$40.NewtonWorldSetCreateDestroyContactCallback$destroyContact_UP$FUNC);
    public static final FunctionDescriptor NewtonWorldSetCreateDestroyContactCallback$destroyContact_DOWN$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonWorldSetCreateDestroyContactCallback$destroyContact_DOWN$MH = RuntimeHelper.downcallHandle(
        constants$40.NewtonWorldSetCreateDestroyContactCallback$destroyContact_DOWN$FUNC
    );
    public static final FunctionDescriptor NewtonWorldSetCreateDestroyContactCallback$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonWorldSetCreateDestroyContactCallback$MH = RuntimeHelper.downcallHandle(
        "NewtonWorldSetCreateDestroyContactCallback",
        constants$40.NewtonWorldSetCreateDestroyContactCallback$FUNC
    );
}


