// Generated by jextract

package crab.newton.internal;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
public class constants$16 {

	public static final FunctionDescriptor NewtonSliderCallback$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
	public static final MethodHandle NewtonSliderCallback$MH = RuntimeHelper.downcallHandle(
        constants$16.NewtonSliderCallback$FUNC, false
    );
	public static final FunctionDescriptor NewtonUniversalCallback$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
	public static final MethodHandle NewtonUniversalCallback$MH = RuntimeHelper.downcallHandle(
        constants$16.NewtonUniversalCallback$FUNC, false
    );
	public static final FunctionDescriptor NewtonCorkscrewCallback$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
	public static final MethodHandle NewtonCorkscrewCallback$MH = RuntimeHelper.downcallHandle(
        constants$16.NewtonCorkscrewCallback$FUNC, false
    );
}


