// Generated by jextract

package crab.newton.internal;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
public class constants$73 {

	public static final FunctionDescriptor NewtonContactGetMaterial$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
	public static final MethodHandle NewtonContactGetMaterial$MH = RuntimeHelper.downcallHandle(
        "NewtonContactGetMaterial",
        constants$73.NewtonContactGetMaterial$FUNC, false
    );
	public static final FunctionDescriptor NewtonContactGetCollision0$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
	public static final MethodHandle NewtonContactGetCollision0$MH = RuntimeHelper.downcallHandle(
        "NewtonContactGetCollision0",
        constants$73.NewtonContactGetCollision0$FUNC, false
    );
	public static final FunctionDescriptor NewtonContactGetCollision1$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
	public static final MethodHandle NewtonContactGetCollision1$MH = RuntimeHelper.downcallHandle(
        "NewtonContactGetCollision1",
        constants$73.NewtonContactGetCollision1$FUNC, false
    );
	public static final FunctionDescriptor NewtonContactGetCollisionID0$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
	public static final MethodHandle NewtonContactGetCollisionID0$MH = RuntimeHelper.downcallHandle(
        "NewtonContactGetCollisionID0",
        constants$73.NewtonContactGetCollisionID0$FUNC, false
    );
	public static final FunctionDescriptor NewtonContactGetCollisionID1$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
	public static final MethodHandle NewtonContactGetCollisionID1$MH = RuntimeHelper.downcallHandle(
        "NewtonContactGetCollisionID1",
        constants$73.NewtonContactGetCollisionID1$FUNC, false
    );
	public static final FunctionDescriptor NewtonJointGetUserData$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
	public static final MethodHandle NewtonJointGetUserData$MH = RuntimeHelper.downcallHandle(
        "NewtonJointGetUserData",
        constants$73.NewtonJointGetUserData$FUNC, false
    );
}


