// Generated by jextract

package crab.newton.internal;

import java.lang.invoke.MethodHandle;
import java.lang.foreign.*;
import crab.newton.callbacks.*;
public final class constants$7 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$7() {}
    public static final FunctionDescriptor NewtonUserMeshCollisionAABBTest$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final FunctionDescriptor NewtonUserMeshCollisionAABBTest_UP$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonUserMeshCollisionAABBTest_UP$MH = RuntimeHelper.upcallHandle(NewtonUserMeshCollisionAABBTest.class, "apply", constants$7.NewtonUserMeshCollisionAABBTest_UP$FUNC);
    public static final FunctionDescriptor NewtonUserMeshCollisionAABBTest_DOWN$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonUserMeshCollisionAABBTest_DOWN$MH = RuntimeHelper.downcallHandle(
        constants$7.NewtonUserMeshCollisionAABBTest_DOWN$FUNC
    );
    public static final FunctionDescriptor NewtonUserMeshCollisionGetFacesInAABB$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final FunctionDescriptor NewtonUserMeshCollisionGetFacesInAABB_UP$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonUserMeshCollisionGetFacesInAABB_UP$MH = RuntimeHelper.upcallHandle(NewtonUserMeshCollisionGetFacesInAABB.class, "apply", constants$7.NewtonUserMeshCollisionGetFacesInAABB_UP$FUNC);
    public static final FunctionDescriptor NewtonUserMeshCollisionGetFacesInAABB_DOWN$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonUserMeshCollisionGetFacesInAABB_DOWN$MH = RuntimeHelper.downcallHandle(
        constants$7.NewtonUserMeshCollisionGetFacesInAABB_DOWN$FUNC
    );
    public static final FunctionDescriptor NewtonUserMeshCollisionCollideCallback$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final FunctionDescriptor NewtonUserMeshCollisionCollideCallback_UP$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonUserMeshCollisionCollideCallback_UP$MH = RuntimeHelper.upcallHandle(NewtonUserMeshCollisionCollideCallback.class, "apply", constants$7.NewtonUserMeshCollisionCollideCallback_UP$FUNC);
    public static final FunctionDescriptor NewtonUserMeshCollisionCollideCallback_DOWN$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonUserMeshCollisionCollideCallback_DOWN$MH = RuntimeHelper.downcallHandle(
        constants$7.NewtonUserMeshCollisionCollideCallback_DOWN$FUNC
    );
}


