// Generated by jextract

package crab.newton.internal;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
public class constants$58 {

	public static final FunctionDescriptor NewtonGetEulerAngle$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
	public static final MethodHandle NewtonGetEulerAngle$MH = RuntimeHelper.downcallHandle(
        "NewtonGetEulerAngle",
        constants$58.NewtonGetEulerAngle$FUNC, false
    );
	public static final FunctionDescriptor NewtonCalculateSpringDamperAcceleration$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
	public static final MethodHandle NewtonCalculateSpringDamperAcceleration$MH = RuntimeHelper.downcallHandle(
        "NewtonCalculateSpringDamperAcceleration",
        constants$58.NewtonCalculateSpringDamperAcceleration$FUNC, false
    );
	public static final FunctionDescriptor NewtonCreateDynamicBody$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
	public static final MethodHandle NewtonCreateDynamicBody$MH = RuntimeHelper.downcallHandle(
        "NewtonCreateDynamicBody",
        constants$58.NewtonCreateDynamicBody$FUNC, false
    );
	public static final FunctionDescriptor NewtonCreateKinematicBody$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
	public static final MethodHandle NewtonCreateKinematicBody$MH = RuntimeHelper.downcallHandle(
        "NewtonCreateKinematicBody",
        constants$58.NewtonCreateKinematicBody$FUNC, false
    );
	public static final FunctionDescriptor NewtonCreateAsymetricDynamicBody$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
	public static final MethodHandle NewtonCreateAsymetricDynamicBody$MH = RuntimeHelper.downcallHandle(
        "NewtonCreateAsymetricDynamicBody",
        constants$58.NewtonCreateAsymetricDynamicBody$FUNC, false
    );
	public static final FunctionDescriptor NewtonDestroyBody$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
	public static final MethodHandle NewtonDestroyBody$MH = RuntimeHelper.downcallHandle(
        "NewtonDestroyBody",
        constants$58.NewtonDestroyBody$FUNC, false
    );
}


