// Generated by jextract
package crab.newton.internal;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
public class constants$41 {

    public static final FunctionDescriptor NewtonCollisionSetMode$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    public static final MethodHandle NewtonCollisionSetMode$MH = RuntimeHelper.downcallHandle(
        "NewtonCollisionSetMode",
        constants$41.NewtonCollisionSetMode$FUNC
    );
    public static final FunctionDescriptor NewtonConvexHullGetFaceIndices$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonConvexHullGetFaceIndices$MH = RuntimeHelper.downcallHandle(
        "NewtonConvexHullGetFaceIndices",
        constants$41.NewtonConvexHullGetFaceIndices$FUNC
    );
    public static final FunctionDescriptor NewtonConvexHullGetVertexData$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonConvexHullGetVertexData$MH = RuntimeHelper.downcallHandle(
        "NewtonConvexHullGetVertexData",
        constants$41.NewtonConvexHullGetVertexData$FUNC
    );
    public static final FunctionDescriptor NewtonConvexCollisionCalculateVolume$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonConvexCollisionCalculateVolume$MH = RuntimeHelper.downcallHandle(
        "NewtonConvexCollisionCalculateVolume",
        constants$41.NewtonConvexCollisionCalculateVolume$FUNC
    );
    public static final FunctionDescriptor NewtonConvexCollisionCalculateInertialMatrix$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonConvexCollisionCalculateInertialMatrix$MH = RuntimeHelper.downcallHandle(
        "NewtonConvexCollisionCalculateInertialMatrix",
        constants$41.NewtonConvexCollisionCalculateInertialMatrix$FUNC
    );
    public static final FunctionDescriptor NewtonConvexCollisionCalculateBuoyancyVolume$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonConvexCollisionCalculateBuoyancyVolume$MH = RuntimeHelper.downcallHandle(
        "NewtonConvexCollisionCalculateBuoyancyVolume",
        constants$41.NewtonConvexCollisionCalculateBuoyancyVolume$FUNC
    );
}


