// Generated by jextract

package crab.newton.internal;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
public class constants$5 {

	public static final FunctionDescriptor NewtonOnJointSerializationCallback$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
	public static final MethodHandle NewtonOnJointSerializationCallback$MH = RuntimeHelper.downcallHandle(
        constants$5.NewtonOnJointSerializationCallback$FUNC, false
    );
	public static final FunctionDescriptor NewtonOnJointDeserializationCallback$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
	public static final MethodHandle NewtonOnJointDeserializationCallback$MH = RuntimeHelper.downcallHandle(
        constants$5.NewtonOnJointDeserializationCallback$FUNC, false
    );
	public static final FunctionDescriptor NewtonOnUserCollisionSerializationCallback$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
	public static final MethodHandle NewtonOnUserCollisionSerializationCallback$MH = RuntimeHelper.downcallHandle(
        constants$5.NewtonOnUserCollisionSerializationCallback$FUNC, false
    );
}


