// Generated by jextract
package crab.newton.internal;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
public class constants$15 {

    public static final FunctionDescriptor NewtonCollisionIterator$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    public static final MethodHandle NewtonCollisionIterator$MH = RuntimeHelper.downcallHandle(
        constants$15.NewtonCollisionIterator$FUNC
    );
    public static final FunctionDescriptor NewtonBallCallback$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    public static final MethodHandle NewtonBallCallback$MH = RuntimeHelper.downcallHandle(
        constants$15.NewtonBallCallback$FUNC
    );
    public static final FunctionDescriptor NewtonHingeCallback$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonHingeCallback$MH = RuntimeHelper.downcallHandle(
        constants$15.NewtonHingeCallback$FUNC
    );
}


