// Generated by jextract

package crab.newton.internal;

import java.lang.invoke.MethodHandle;
import java.lang.foreign.*;
import crab.newton.callbacks.*;
public final class constants$2 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$2() {}
    public static final FunctionDescriptor NewtonWorldListenerDebugCallback$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final FunctionDescriptor NewtonWorldListenerDebugCallback_UP$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonWorldListenerDebugCallback_UP$MH = RuntimeHelper.upcallHandle(NewtonWorldListenerDebugCallback.class, "apply", constants$2.NewtonWorldListenerDebugCallback_UP$FUNC);
    public static final FunctionDescriptor NewtonWorldListenerDebugCallback_DOWN$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonWorldListenerDebugCallback_DOWN$MH = RuntimeHelper.downcallHandle(
        constants$2.NewtonWorldListenerDebugCallback_DOWN$FUNC
    );
    public static final FunctionDescriptor NewtonWorldListenerBodyDestroyCallback$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final FunctionDescriptor NewtonWorldListenerBodyDestroyCallback_UP$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonWorldListenerBodyDestroyCallback_UP$MH = RuntimeHelper.upcallHandle(NewtonWorldListenerBodyDestroyCallback.class, "apply", constants$2.NewtonWorldListenerBodyDestroyCallback_UP$FUNC);
    public static final FunctionDescriptor NewtonWorldListenerBodyDestroyCallback_DOWN$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonWorldListenerBodyDestroyCallback_DOWN$MH = RuntimeHelper.downcallHandle(
        constants$2.NewtonWorldListenerBodyDestroyCallback_DOWN$FUNC
    );
    public static final FunctionDescriptor NewtonWorldUpdateListenerCallback$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    public static final FunctionDescriptor NewtonWorldUpdateListenerCallback_UP$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    public static final MethodHandle NewtonWorldUpdateListenerCallback_UP$MH = RuntimeHelper.upcallHandle(NewtonWorldUpdateListenerCallback.class, "apply", constants$2.NewtonWorldUpdateListenerCallback_UP$FUNC);
    public static final FunctionDescriptor NewtonWorldUpdateListenerCallback_DOWN$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    public static final MethodHandle NewtonWorldUpdateListenerCallback_DOWN$MH = RuntimeHelper.downcallHandle(
        constants$2.NewtonWorldUpdateListenerCallback_DOWN$FUNC
    );
}


