// Generated by jextract
package crab.newton.internal;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
public class constants$52 {

    public static final FunctionDescriptor NewtonStaticCollisionSetDebugCallback$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonStaticCollisionSetDebugCallback$MH = RuntimeHelper.downcallHandle(
        "NewtonStaticCollisionSetDebugCallback",
        constants$52.NewtonStaticCollisionSetDebugCallback$FUNC
    );
    public static final FunctionDescriptor NewtonCollisionCreateInstance$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonCollisionCreateInstance$MH = RuntimeHelper.downcallHandle(
        "NewtonCollisionCreateInstance",
        constants$52.NewtonCollisionCreateInstance$FUNC
    );
    public static final FunctionDescriptor NewtonCollisionGetType$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonCollisionGetType$MH = RuntimeHelper.downcallHandle(
        "NewtonCollisionGetType",
        constants$52.NewtonCollisionGetType$FUNC
    );
    public static final FunctionDescriptor NewtonCollisionIsConvexShape$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonCollisionIsConvexShape$MH = RuntimeHelper.downcallHandle(
        "NewtonCollisionIsConvexShape",
        constants$52.NewtonCollisionIsConvexShape$FUNC
    );
    public static final FunctionDescriptor NewtonCollisionIsStaticShape$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonCollisionIsStaticShape$MH = RuntimeHelper.downcallHandle(
        "NewtonCollisionIsStaticShape",
        constants$52.NewtonCollisionIsStaticShape$FUNC
    );
    public static final FunctionDescriptor NewtonCollisionSetUserData$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonCollisionSetUserData$MH = RuntimeHelper.downcallHandle(
        "NewtonCollisionSetUserData",
        constants$52.NewtonCollisionSetUserData$FUNC
    );
}


