// Generated by jextract

package crab.newton.internal;

import java.lang.invoke.MethodHandle;
import java.lang.foreign.*;
import crab.newton.callbacks.*;
public final class constants$27 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$27() {}
    public static final FunctionDescriptor NewtonSerializeScene$bodyCallback_DOWN$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonSerializeScene$bodyCallback_DOWN$MH = RuntimeHelper.downcallHandle(
        constants$27.NewtonSerializeScene$bodyCallback_DOWN$FUNC
    );
    public static final FunctionDescriptor NewtonSerializeScene$serializeCallback$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    public static final FunctionDescriptor NewtonSerializeScene$serializeCallback_UP$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    public static final MethodHandle NewtonSerializeScene$serializeCallback_UP$MH = RuntimeHelper.upcallHandle(NewtonSerializeScene$serializeCallback.class, "apply", constants$27.NewtonSerializeScene$serializeCallback_UP$FUNC);
    public static final FunctionDescriptor NewtonSerializeScene$serializeCallback_DOWN$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    public static final MethodHandle NewtonSerializeScene$serializeCallback_DOWN$MH = RuntimeHelper.downcallHandle(
        constants$27.NewtonSerializeScene$serializeCallback_DOWN$FUNC
    );
    public static final FunctionDescriptor NewtonSerializeScene$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonSerializeScene$MH = RuntimeHelper.downcallHandle(
        "NewtonSerializeScene",
        constants$27.NewtonSerializeScene$FUNC
    );
    public static final FunctionDescriptor NewtonDeserializeScene$bodyCallback$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final FunctionDescriptor NewtonDeserializeScene$bodyCallback_UP$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonDeserializeScene$bodyCallback_UP$MH = RuntimeHelper.upcallHandle(NewtonDeserializeScene$bodyCallback.class, "apply", constants$27.NewtonDeserializeScene$bodyCallback_UP$FUNC);
    public static final FunctionDescriptor NewtonDeserializeScene$bodyCallback_DOWN$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonDeserializeScene$bodyCallback_DOWN$MH = RuntimeHelper.downcallHandle(
        constants$27.NewtonDeserializeScene$bodyCallback_DOWN$FUNC
    );
}


