// Generated by jextract

package crab.newton.internal;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
public class constants$17 {

	public static final FunctionDescriptor NewtonUserBilateralCallback$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
	public static final MethodHandle NewtonUserBilateralCallback$MH = RuntimeHelper.downcallHandle(
        constants$17.NewtonUserBilateralCallback$FUNC, false
    );
	public static final FunctionDescriptor NewtonUserBilateralGetInfoCallback$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
	public static final MethodHandle NewtonUserBilateralGetInfoCallback$MH = RuntimeHelper.downcallHandle(
        constants$17.NewtonUserBilateralGetInfoCallback$FUNC, false
    );
	public static final FunctionDescriptor NewtonConstraintDestructor$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
	public static final MethodHandle NewtonConstraintDestructor$MH = RuntimeHelper.downcallHandle(
        constants$17.NewtonConstraintDestructor$FUNC, false
    );
}


