// Generated by jextract

package crab.newton.internal;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
public final class constants$77 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$77() {}
    public static final FunctionDescriptor NewtonCollisionAggregateRemoveBody$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonCollisionAggregateRemoveBody$MH = RuntimeHelper.downcallHandle(
        "NewtonCollisionAggregateRemoveBody",
        constants$77.NewtonCollisionAggregateRemoveBody$FUNC
    );
    public static final FunctionDescriptor NewtonCollisionAggregateGetSelfCollision$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonCollisionAggregateGetSelfCollision$MH = RuntimeHelper.downcallHandle(
        "NewtonCollisionAggregateGetSelfCollision",
        constants$77.NewtonCollisionAggregateGetSelfCollision$FUNC
    );
    public static final FunctionDescriptor NewtonCollisionAggregateSetSelfCollision$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    public static final MethodHandle NewtonCollisionAggregateSetSelfCollision$MH = RuntimeHelper.downcallHandle(
        "NewtonCollisionAggregateSetSelfCollision",
        constants$77.NewtonCollisionAggregateSetSelfCollision$FUNC
    );
    public static final FunctionDescriptor NewtonSetEulerAngle$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonSetEulerAngle$MH = RuntimeHelper.downcallHandle(
        "NewtonSetEulerAngle",
        constants$77.NewtonSetEulerAngle$FUNC
    );
    public static final FunctionDescriptor NewtonGetEulerAngle$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonGetEulerAngle$MH = RuntimeHelper.downcallHandle(
        "NewtonGetEulerAngle",
        constants$77.NewtonGetEulerAngle$FUNC
    );
    public static final FunctionDescriptor NewtonCalculateSpringDamperAcceleration$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    public static final MethodHandle NewtonCalculateSpringDamperAcceleration$MH = RuntimeHelper.downcallHandle(
        "NewtonCalculateSpringDamperAcceleration",
        constants$77.NewtonCalculateSpringDamperAcceleration$FUNC
    );
}


