// Generated by jextract

package crab.newton.internal;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
public final class constants$125 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$125() {}
    public static final FunctionDescriptor NewtonMeshCreateNextLayer$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonMeshCreateNextLayer$MH = RuntimeHelper.downcallHandle(
        "NewtonMeshCreateNextLayer",
        constants$125.NewtonMeshCreateNextLayer$FUNC
    );
    public static final FunctionDescriptor NewtonMeshGetTotalFaceCount$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonMeshGetTotalFaceCount$MH = RuntimeHelper.downcallHandle(
        "NewtonMeshGetTotalFaceCount",
        constants$125.NewtonMeshGetTotalFaceCount$FUNC
    );
    public static final FunctionDescriptor NewtonMeshGetTotalIndexCount$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonMeshGetTotalIndexCount$MH = RuntimeHelper.downcallHandle(
        "NewtonMeshGetTotalIndexCount",
        constants$125.NewtonMeshGetTotalIndexCount$FUNC
    );
    public static final FunctionDescriptor NewtonMeshGetFaces$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonMeshGetFaces$MH = RuntimeHelper.downcallHandle(
        "NewtonMeshGetFaces",
        constants$125.NewtonMeshGetFaces$FUNC
    );
    public static final FunctionDescriptor NewtonMeshGetVertexCount$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonMeshGetVertexCount$MH = RuntimeHelper.downcallHandle(
        "NewtonMeshGetVertexCount",
        constants$125.NewtonMeshGetVertexCount$FUNC
    );
    public static final FunctionDescriptor NewtonMeshGetVertexStrideInByte$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonMeshGetVertexStrideInByte$MH = RuntimeHelper.downcallHandle(
        "NewtonMeshGetVertexStrideInByte",
        constants$125.NewtonMeshGetVertexStrideInByte$FUNC
    );
}


