// Generated by jextract

package crab.newton.internal;

import java.lang.invoke.MethodHandle;
import java.lang.foreign.*;
import crab.newton.callbacks.*;
public final class constants$12 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$12() {}
    public static final FunctionDescriptor NewtonFractureCompoundCollisionReconstructMainMeshCallBack$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final FunctionDescriptor NewtonFractureCompoundCollisionReconstructMainMeshCallBack_UP$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonFractureCompoundCollisionReconstructMainMeshCallBack_UP$MH = RuntimeHelper.upcallHandle(NewtonFractureCompoundCollisionReconstructMainMeshCallBack.class, "apply", constants$12.NewtonFractureCompoundCollisionReconstructMainMeshCallBack_UP$FUNC);
    public static final FunctionDescriptor NewtonFractureCompoundCollisionReconstructMainMeshCallBack_DOWN$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonFractureCompoundCollisionReconstructMainMeshCallBack_DOWN$MH = RuntimeHelper.downcallHandle(
        constants$12.NewtonFractureCompoundCollisionReconstructMainMeshCallBack_DOWN$FUNC
    );
    public static final FunctionDescriptor NewtonWorldRayPrefilterCallback$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final FunctionDescriptor NewtonWorldRayPrefilterCallback_UP$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonWorldRayPrefilterCallback_UP$MH = RuntimeHelper.upcallHandle(NewtonWorldRayPrefilterCallback.class, "apply", constants$12.NewtonWorldRayPrefilterCallback_UP$FUNC);
    public static final FunctionDescriptor NewtonWorldRayPrefilterCallback_DOWN$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonWorldRayPrefilterCallback_DOWN$MH = RuntimeHelper.downcallHandle(
        constants$12.NewtonWorldRayPrefilterCallback_DOWN$FUNC
    );
    public static final FunctionDescriptor NewtonWorldRayFilterCallback$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    public static final FunctionDescriptor NewtonWorldRayFilterCallback_UP$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    public static final MethodHandle NewtonWorldRayFilterCallback_UP$MH = RuntimeHelper.upcallHandle(NewtonWorldRayFilterCallback.class, "apply", constants$12.NewtonWorldRayFilterCallback_UP$FUNC);
    public static final FunctionDescriptor NewtonWorldRayFilterCallback_DOWN$FUNC = FunctionDescriptor.of(Constants$root.C_FLOAT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_FLOAT$LAYOUT
    );
    public static final MethodHandle NewtonWorldRayFilterCallback_DOWN$MH = RuntimeHelper.downcallHandle(
        constants$12.NewtonWorldRayFilterCallback_DOWN$FUNC
    );
}


