// Generated by jextract

package crab.newton.internal;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
public class constants$91 {

	public static final FunctionDescriptor NewtonMeshTriangulate$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
	public static final MethodHandle NewtonMeshTriangulate$MH = RuntimeHelper.downcallHandle(
        "NewtonMeshTriangulate",
        constants$91.NewtonMeshTriangulate$FUNC, false
    );
	public static final FunctionDescriptor NewtonMeshUnion$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
	public static final MethodHandle NewtonMeshUnion$MH = RuntimeHelper.downcallHandle(
        "NewtonMeshUnion",
        constants$91.NewtonMeshUnion$FUNC, false
    );
	public static final FunctionDescriptor NewtonMeshDifference$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
	public static final MethodHandle NewtonMeshDifference$MH = RuntimeHelper.downcallHandle(
        "NewtonMeshDifference",
        constants$91.NewtonMeshDifference$FUNC, false
    );
	public static final FunctionDescriptor NewtonMeshIntersection$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
	public static final MethodHandle NewtonMeshIntersection$MH = RuntimeHelper.downcallHandle(
        "NewtonMeshIntersection",
        constants$91.NewtonMeshIntersection$FUNC, false
    );
	public static final FunctionDescriptor NewtonMeshClip$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
	public static final MethodHandle NewtonMeshClip$MH = RuntimeHelper.downcallHandle(
        "NewtonMeshClip",
        constants$91.NewtonMeshClip$FUNC, false
    );
	public static final FunctionDescriptor NewtonMeshConvexMeshIntersection$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
	public static final MethodHandle NewtonMeshConvexMeshIntersection$MH = RuntimeHelper.downcallHandle(
        "NewtonMeshConvexMeshIntersection",
        constants$91.NewtonMeshConvexMeshIntersection$FUNC, false
    );
}


