// Generated by jextract

package crab.newton.internal;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
public final class constants$93 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$93() {}
    public static final FunctionDescriptor NewtonBodyGetFirstContactJoint$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonBodyGetFirstContactJoint$MH = RuntimeHelper.downcallHandle(
        "NewtonBodyGetFirstContactJoint",
        constants$93.NewtonBodyGetFirstContactJoint$FUNC
    );
    public static final FunctionDescriptor NewtonBodyGetNextContactJoint$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonBodyGetNextContactJoint$MH = RuntimeHelper.downcallHandle(
        "NewtonBodyGetNextContactJoint",
        constants$93.NewtonBodyGetNextContactJoint$FUNC
    );
    public static final FunctionDescriptor NewtonBodyFindContact$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonBodyFindContact$MH = RuntimeHelper.downcallHandle(
        "NewtonBodyFindContact",
        constants$93.NewtonBodyFindContact$FUNC
    );
    public static final FunctionDescriptor NewtonContactJointGetFirstContact$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonContactJointGetFirstContact$MH = RuntimeHelper.downcallHandle(
        "NewtonContactJointGetFirstContact",
        constants$93.NewtonContactJointGetFirstContact$FUNC
    );
    public static final FunctionDescriptor NewtonContactJointGetNextContact$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonContactJointGetNextContact$MH = RuntimeHelper.downcallHandle(
        "NewtonContactJointGetNextContact",
        constants$93.NewtonContactJointGetNextContact$FUNC
    );
    public static final FunctionDescriptor NewtonContactJointGetContactCount$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    public static final MethodHandle NewtonContactJointGetContactCount$MH = RuntimeHelper.downcallHandle(
        "NewtonContactJointGetContactCount",
        constants$93.NewtonContactJointGetContactCount$FUNC
    );
}


