// Generated by jextract

package crab.newton.callbacks;

import java.lang.foreign.*;
import crab.newton.internal.*;
/**
 * {@snippet :
 * void (*NewtonCreateUserMeshCollision$destroyCallback)(void*);
 * }
 */
public interface NewtonCreateUserMeshCollision$destroyCallback {

    void apply(java.lang.foreign.MemorySegment me);
    static MemorySegment allocate(NewtonCreateUserMeshCollision$destroyCallback fi, SegmentScope scope) {
        return RuntimeHelper.upcallStub(constants$64.NewtonCreateUserMeshCollision$destroyCallback_UP$MH, fi, constants$64.NewtonCreateUserMeshCollision$destroyCallback$FUNC, scope);
    }
    static NewtonCreateUserMeshCollision$destroyCallback ofAddress(MemorySegment addr, SegmentScope scope) {
        MemorySegment symbol = MemorySegment.ofAddress(addr.address(), 0, scope);
        return (java.lang.foreign.MemorySegment _me) -> {
            try {
                constants$65.NewtonCreateUserMeshCollision$destroyCallback_DOWN$MH.invokeExact(symbol, _me);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


