// Generated by jextract

package crab.newton.callbacks;

import java.lang.foreign.*;
import crab.newton.internal.*;
/**
 * {@snippet :
 * float (*NewtonHeightFieldRayCastCallback)(struct NewtonBody* body,struct NewtonCollision* heightFieldCollision,float intersection,int row,int col,float* normal,int faceId,void* usedData);
 * }
 */
public interface NewtonHeightFieldRayCastCallback {

    float apply(java.lang.foreign.MemorySegment body, java.lang.foreign.MemorySegment heightFieldCollision, float intersection, int row, int col, java.lang.foreign.MemorySegment normal, int faceId, java.lang.foreign.MemorySegment usedData);
    static MemorySegment allocate(NewtonHeightFieldRayCastCallback fi, SegmentScope scope) {
        return RuntimeHelper.upcallStub(constants$8.NewtonHeightFieldRayCastCallback_UP$MH, fi, constants$8.NewtonHeightFieldRayCastCallback$FUNC, scope);
    }
    static NewtonHeightFieldRayCastCallback ofAddress(MemorySegment addr, SegmentScope scope) {
        MemorySegment symbol = MemorySegment.ofAddress(addr.address(), 0, scope);
        return (java.lang.foreign.MemorySegment _body, java.lang.foreign.MemorySegment _heightFieldCollision, float _intersection, int _row, int _col, java.lang.foreign.MemorySegment _normal, int _faceId, java.lang.foreign.MemorySegment _usedData) -> {
            try {
                return (float)constants$8.NewtonHeightFieldRayCastCallback_DOWN$MH.invokeExact(symbol, _body, _heightFieldCollision, _intersection, _row, _col, _normal, _faceId, _usedData);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


