package crab.newton.callbacks;// Generated by jextract

import java.lang.foreign.*;
import crab.newton.internal.*;

public interface NewtonFreeMemory {

    void apply(java.lang.foreign.MemoryAddress ptr, int sizeInBytes);
    static MemorySegment allocate(NewtonFreeMemory fi, MemorySession session) {
        return RuntimeHelper.upcallStub(NewtonFreeMemory.class, fi, constants$0.NewtonFreeMemory$FUNC, session);
    }
    static NewtonFreeMemory ofAddress(MemoryAddress addr, MemorySession session) {
        MemorySegment symbol = MemorySegment.ofAddress(addr, 0, session);
        return (java.lang.foreign.MemoryAddress _ptr, int _sizeInBytes) -> {
            try {
                constants$0.NewtonFreeMemory$MH.invokeExact((Addressable)symbol, (java.lang.foreign.Addressable)_ptr, _sizeInBytes);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


