package crab.newton.callbacks;// Generated by jextract

import java.lang.foreign.*;
import crab.newton.internal.*;

public interface NewtonContactsProcess {

    void apply(java.lang.foreign.MemoryAddress contact, float timestep, int threadIndex);
    static MemorySegment allocate(NewtonContactsProcess fi, MemorySession session) {
        return RuntimeHelper.upcallStub(NewtonContactsProcess.class, fi, constants$13.NewtonContactsProcess$FUNC, session);
    }
    static NewtonContactsProcess ofAddress(MemoryAddress addr, MemorySession session) {
        MemorySegment symbol = MemorySegment.ofAddress(addr, 0, session);
        return (java.lang.foreign.MemoryAddress _contact, float _timestep, int _threadIndex) -> {
            try {
                constants$13.NewtonContactsProcess$MH.invokeExact((Addressable)symbol, (java.lang.foreign.Addressable)_contact, _timestep, _threadIndex);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


