// Generated by jextract

package crab.newton.callbacks;

import java.lang.foreign.*;
import crab.newton.internal.*;
/**
 * {@snippet :
 * void (*NewtonOnBodyDeserializationCallback)(struct NewtonBody* body,void* userData,void (*function)(void*,void*,int),void* serializeHandle);
 * }
 */
public interface NewtonOnBodyDeserializationCallback {

    void apply(java.lang.foreign.MemorySegment body0, java.lang.foreign.MemorySegment body1, java.lang.foreign.MemorySegment function, java.lang.foreign.MemorySegment serializeHandle);
    static MemorySegment allocate(NewtonOnBodyDeserializationCallback fi, SegmentScope scope) {
        return RuntimeHelper.upcallStub(constants$4.NewtonOnBodyDeserializationCallback_UP$MH, fi, constants$4.NewtonOnBodyDeserializationCallback$FUNC, scope);
    }
    static NewtonOnBodyDeserializationCallback ofAddress(MemorySegment addr, SegmentScope scope) {
        MemorySegment symbol = MemorySegment.ofAddress(addr.address(), 0, scope);
        return (java.lang.foreign.MemorySegment _body0, java.lang.foreign.MemorySegment _body1, java.lang.foreign.MemorySegment _function, java.lang.foreign.MemorySegment _serializeHandle) -> {
            try {
                constants$4.NewtonOnBodyDeserializationCallback_DOWN$MH.invokeExact(symbol, _body0, _body1, _function, _serializeHandle);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


