// Generated by jextract

package crab.newton.callbacks;

import java.lang.foreign.*;
import crab.newton.internal.*;
/**
 * {@snippet :
 * void (*NewtonWorldListenerSetPreUpdateCallback$callback)(struct NewtonWorld*,void*,float);
 * }
 */
public interface NewtonWorldListenerSetPreUpdateCallback$callback {

    void apply(java.lang.foreign.MemorySegment world, java.lang.foreign.MemorySegment listenerUserData, float timestep);
    static MemorySegment allocate(NewtonWorldListenerSetPreUpdateCallback$callback fi, SegmentScope scope) {
        return RuntimeHelper.upcallStub(constants$35.NewtonWorldListenerSetPreUpdateCallback$callback_UP$MH, fi, constants$35.NewtonWorldListenerSetPreUpdateCallback$callback$FUNC, scope);
    }
    static NewtonWorldListenerSetPreUpdateCallback$callback ofAddress(MemorySegment addr, SegmentScope scope) {
        MemorySegment symbol = MemorySegment.ofAddress(addr.address(), 0, scope);
        return (java.lang.foreign.MemorySegment _world, java.lang.foreign.MemorySegment _listenerUserData, float _timestep) -> {
            try {
                constants$35.NewtonWorldListenerSetPreUpdateCallback$callback_DOWN$MH.invokeExact(symbol, _world, _listenerUserData, _timestep);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


