// Generated by jextract

package crab.newton.callbacks;

import java.lang.foreign.*;
import crab.newton.internal.*;
/**
 * {@snippet :
 * void (*NewtonBallCallback)(struct NewtonJoint* ball,float timestep);
 * }
 */
public interface NewtonBallCallback {

    void apply(java.lang.foreign.MemorySegment ball, float timestep);
    static MemorySegment allocate(NewtonBallCallback fi, SegmentScope scope) {
        return RuntimeHelper.upcallStub(constants$15.NewtonBallCallback_UP$MH, fi, constants$15.NewtonBallCallback$FUNC, scope);
    }
    static NewtonBallCallback ofAddress(MemorySegment addr, SegmentScope scope) {
        MemorySegment symbol = MemorySegment.ofAddress(addr.address(), 0, scope);
        return (java.lang.foreign.MemorySegment _ball, float _timestep) -> {
            try {
                constants$15.NewtonBallCallback_DOWN$MH.invokeExact(symbol, _ball, _timestep);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


