package crab.newton.callbacks;// Generated by jextract

import java.lang.foreign.*;
import crab.newton.internal.*;

public interface NewtonWorldListenerDebugCallback {

    void apply(java.lang.foreign.MemoryAddress world, java.lang.foreign.MemoryAddress listener, java.lang.foreign.MemoryAddress debugContext);
    static MemorySegment allocate(NewtonWorldListenerDebugCallback fi, MemorySession session) {
        return RuntimeHelper.upcallStub(NewtonWorldListenerDebugCallback.class, fi, constants$2.NewtonWorldListenerDebugCallback$FUNC, session);
    }
    static NewtonWorldListenerDebugCallback ofAddress(MemoryAddress addr, MemorySession session) {
        MemorySegment symbol = MemorySegment.ofAddress(addr, 0, session);
        return (java.lang.foreign.MemoryAddress _world, java.lang.foreign.MemoryAddress _listener, java.lang.foreign.MemoryAddress _debugContext) -> {
            try {
                constants$2.NewtonWorldListenerDebugCallback$MH.invokeExact((Addressable)symbol, (java.lang.foreign.Addressable)_world, (java.lang.foreign.Addressable)_listener, (java.lang.foreign.Addressable)_debugContext);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


