package crab.newton.callbacks;// Generated by jextract

import java.lang.foreign.*;
import crab.newton.internal.*;

public interface NewtonOnBodyDeserializationCallback {

    void apply(java.lang.foreign.MemoryAddress body, java.lang.foreign.MemoryAddress userData, java.lang.foreign.MemoryAddress function, java.lang.foreign.MemoryAddress serializeHandle);
    static MemorySegment allocate(NewtonOnBodyDeserializationCallback fi, MemorySession session) {
        return RuntimeHelper.upcallStub(NewtonOnBodyDeserializationCallback.class, fi, constants$4.NewtonOnBodyDeserializationCallback$FUNC, session);
    }
    static NewtonOnBodyDeserializationCallback ofAddress(MemoryAddress addr, MemorySession session) {
        MemorySegment symbol = MemorySegment.ofAddress(addr, 0, session);
        return (java.lang.foreign.MemoryAddress _body, java.lang.foreign.MemoryAddress _userData, java.lang.foreign.MemoryAddress _function, java.lang.foreign.MemoryAddress _serializeHandle) -> {
            try {
                constants$4.NewtonOnBodyDeserializationCallback$MH.invokeExact((Addressable)symbol, (java.lang.foreign.Addressable)_body, (java.lang.foreign.Addressable)_userData, (java.lang.foreign.Addressable)_function, (java.lang.foreign.Addressable)_serializeHandle);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


