// Generated by jextract

package crab.newton.callbacks;

import java.lang.foreign.*;
import crab.newton.internal.*;
/**
 * {@snippet :
 * void (*NewtonSetJointSerializationCallbacks$serializeJoint)(struct NewtonJoint*,void (*)(void*,void*,int),void*);
 * }
 */
public interface NewtonSetJointSerializationCallbacks$serializeJoint {

    void apply(java.lang.foreign.MemorySegment body, java.lang.foreign.MemorySegment mainMesh, java.lang.foreign.MemorySegment fracturedCompountCollision);
    static MemorySegment allocate(NewtonSetJointSerializationCallbacks$serializeJoint fi, SegmentScope scope) {
        return RuntimeHelper.upcallStub(constants$28.NewtonSetJointSerializationCallbacks$serializeJoint_UP$MH, fi, constants$28.NewtonSetJointSerializationCallbacks$serializeJoint$FUNC, scope);
    }
    static NewtonSetJointSerializationCallbacks$serializeJoint ofAddress(MemorySegment addr, SegmentScope scope) {
        MemorySegment symbol = MemorySegment.ofAddress(addr.address(), 0, scope);
        return (java.lang.foreign.MemorySegment _body, java.lang.foreign.MemorySegment _mainMesh, java.lang.foreign.MemorySegment _fracturedCompountCollision) -> {
            try {
                constants$28.NewtonSetJointSerializationCallbacks$serializeJoint_DOWN$MH.invokeExact(symbol, _body, _mainMesh, _fracturedCompountCollision);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


