// Generated by jextract

package crab.newton.callbacks;

import java.lang.foreign.*;
import crab.newton.internal.*;
/**
 * {@snippet :
 * void (*NewtonSetTransform)(struct NewtonBody* body,float* matrix,int threadIndex);
 * }
 */
public interface NewtonSetTransform {

    void apply(java.lang.foreign.MemorySegment world, java.lang.foreign.MemorySegment userData, int threadIndex);
    static MemorySegment allocate(NewtonSetTransform fi, SegmentScope scope) {
        return RuntimeHelper.upcallStub(constants$10.NewtonSetTransform_UP$MH, fi, constants$10.NewtonSetTransform$FUNC, scope);
    }
    static NewtonSetTransform ofAddress(MemorySegment addr, SegmentScope scope) {
        MemorySegment symbol = MemorySegment.ofAddress(addr.address(), 0, scope);
        return (java.lang.foreign.MemorySegment _world, java.lang.foreign.MemorySegment _userData, int _threadIndex) -> {
            try {
                constants$10.NewtonSetTransform_DOWN$MH.invokeExact(symbol, _world, _userData, _threadIndex);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


