package crab.newton.callbacks;// Generated by jextract

import java.lang.foreign.*;
import crab.newton.internal.*;

public interface NewtonCreateContactCallback {

    void apply(java.lang.foreign.MemoryAddress newtonWorld, java.lang.foreign.MemoryAddress contact);
    static MemorySegment allocate(NewtonCreateContactCallback fi, MemorySession session) {
        return RuntimeHelper.upcallStub(NewtonCreateContactCallback.class, fi, constants$1.NewtonCreateContactCallback$FUNC, session);
    }
    static NewtonCreateContactCallback ofAddress(MemoryAddress addr, MemorySession session) {
        MemorySegment symbol = MemorySegment.ofAddress(addr, 0, session);
        return (java.lang.foreign.MemoryAddress _newtonWorld, java.lang.foreign.MemoryAddress _contact) -> {
            try {
                constants$1.NewtonCreateContactCallback$MH.invokeExact((Addressable)symbol, (java.lang.foreign.Addressable)_newtonWorld, (java.lang.foreign.Addressable)_contact);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


