// Generated by jextract

package crab.newton.callbacks;

import java.lang.foreign.*;
import crab.newton.internal.*;
/**
 * {@snippet :
 * void (*NewtonDeserializeCallback)(void* serializeHandle,void* buffer,int size);
 * }
 */
public interface NewtonDeserializeCallback {

    void apply(java.lang.foreign.MemorySegment world, java.lang.foreign.MemorySegment userData, int threadIndex);
    static MemorySegment allocate(NewtonDeserializeCallback fi, SegmentScope scope) {
        return RuntimeHelper.upcallStub(constants$4.NewtonDeserializeCallback_UP$MH, fi, constants$4.NewtonDeserializeCallback$FUNC, scope);
    }
    static NewtonDeserializeCallback ofAddress(MemorySegment addr, SegmentScope scope) {
        MemorySegment symbol = MemorySegment.ofAddress(addr.address(), 0, scope);
        return (java.lang.foreign.MemorySegment _world, java.lang.foreign.MemorySegment _userData, int _threadIndex) -> {
            try {
                constants$4.NewtonDeserializeCallback_DOWN$MH.invokeExact(symbol, _world, _userData, _threadIndex);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


