// Generated by jextract

package crab.newton.callbacks;

import java.lang.foreign.*;
import crab.newton.internal.*;
/**
 * {@snippet :
 * unsigned int (*NewtonWorldCollide$prefilter)(struct NewtonBody*,struct NewtonCollision*,void*);
 * }
 */
public interface NewtonWorldCollide$prefilter {

    int apply(java.lang.foreign.MemorySegment body, java.lang.foreign.MemorySegment collision, java.lang.foreign.MemorySegment userData);
    static MemorySegment allocate(NewtonWorldCollide$prefilter fi, SegmentScope scope) {
        return RuntimeHelper.upcallStub(constants$42.NewtonWorldCollide$prefilter_UP$MH, fi, constants$42.NewtonWorldCollide$prefilter$FUNC, scope);
    }
    static NewtonWorldCollide$prefilter ofAddress(MemorySegment addr, SegmentScope scope) {
        MemorySegment symbol = MemorySegment.ofAddress(addr.address(), 0, scope);
        return (java.lang.foreign.MemorySegment _body, java.lang.foreign.MemorySegment _collision, java.lang.foreign.MemorySegment _userData) -> {
            try {
                return (int)constants$42.NewtonWorldCollide$prefilter_DOWN$MH.invokeExact(symbol, _body, _collision, _userData);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


