// Generated by jextract

package crab.newton.callbacks;

import java.lang.foreign.*;
import crab.newton.internal.*;
/**
 * {@snippet :
 * unsigned int (*NewtonUniversalCallback)(struct NewtonJoint* universal,struct NewtonHingeSliderUpdateDesc* desc);
 * }
 */
public interface NewtonUniversalCallback {

    int apply(java.lang.foreign.MemorySegment corkscrew, java.lang.foreign.MemorySegment desc);
    static MemorySegment allocate(NewtonUniversalCallback fi, SegmentScope scope) {
        return RuntimeHelper.upcallStub(constants$16.NewtonUniversalCallback_UP$MH, fi, constants$16.NewtonUniversalCallback$FUNC, scope);
    }
    static NewtonUniversalCallback ofAddress(MemorySegment addr, SegmentScope scope) {
        MemorySegment symbol = MemorySegment.ofAddress(addr.address(), 0, scope);
        return (java.lang.foreign.MemorySegment _corkscrew, java.lang.foreign.MemorySegment _desc) -> {
            try {
                return (int)constants$16.NewtonUniversalCallback_DOWN$MH.invokeExact(symbol, _corkscrew, _desc);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


