// Generated by jextract

package crab.newton.callbacks;

import java.lang.foreign.*;
import crab.newton.internal.*;
/**
 * {@snippet :
 * void (*NewtonWorldGetDestructorCallback$return)(struct NewtonWorld*);
 * }
 */
public interface NewtonWorldGetDestructorCallback$return {

    void apply(java.lang.foreign.MemorySegment me);
    static MemorySegment allocate(NewtonWorldGetDestructorCallback$return fi, SegmentScope scope) {
        return RuntimeHelper.upcallStub(constants$38.NewtonWorldGetDestructorCallback$return_UP$MH, fi, constants$38.NewtonWorldGetDestructorCallback$return$FUNC, scope);
    }
    static NewtonWorldGetDestructorCallback$return ofAddress(MemorySegment addr, SegmentScope scope) {
        MemorySegment symbol = MemorySegment.ofAddress(addr.address(), 0, scope);
        return (java.lang.foreign.MemorySegment _me) -> {
            try {
                constants$39.NewtonWorldGetDestructorCallback$return_DOWN$MH.invokeExact(symbol, _me);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


