// Generated by jextract

package crab.newton.callbacks;

import java.lang.foreign.*;
import crab.newton.internal.*;
/**
 * {@snippet :
 * void (*NewtonJobTask)(struct NewtonWorld* world,void* userData,int threadIndex);
 * }
 */
public interface NewtonJobTask {

    void apply(java.lang.foreign.MemorySegment world, java.lang.foreign.MemorySegment userData, int threadIndex);
    static MemorySegment allocate(NewtonJobTask fi, SegmentScope scope) {
        return RuntimeHelper.upcallStub(constants$18.NewtonJobTask_UP$MH, fi, constants$18.NewtonJobTask$FUNC, scope);
    }
    static NewtonJobTask ofAddress(MemorySegment addr, SegmentScope scope) {
        MemorySegment symbol = MemorySegment.ofAddress(addr.address(), 0, scope);
        return (java.lang.foreign.MemorySegment _world, java.lang.foreign.MemorySegment _userData, int _threadIndex) -> {
            try {
                constants$18.NewtonJobTask_DOWN$MH.invokeExact(symbol, _world, _userData, _threadIndex);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


