// Generated by jextract

package crab.newton.callbacks;

import java.lang.foreign.*;
import crab.newton.internal.*;
/**
 * {@snippet :
 * int (*NewtonBodyIterator)(struct NewtonBody* body,void* userData);
 * }
 */
public interface NewtonBodyIterator {

    int apply(java.lang.foreign.MemorySegment body, java.lang.foreign.MemorySegment userData);
    static MemorySegment allocate(NewtonBodyIterator fi, SegmentScope scope) {
        return RuntimeHelper.upcallStub(constants$14.NewtonBodyIterator_UP$MH, fi, constants$14.NewtonBodyIterator$FUNC, scope);
    }
    static NewtonBodyIterator ofAddress(MemorySegment addr, SegmentScope scope) {
        MemorySegment symbol = MemorySegment.ofAddress(addr.address(), 0, scope);
        return (java.lang.foreign.MemorySegment _body, java.lang.foreign.MemorySegment _userData) -> {
            try {
                return (int)constants$14.NewtonBodyIterator_DOWN$MH.invokeExact(symbol, _body, _userData);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


