// Generated by jextract

package crab.newton.callbacks;

import java.lang.foreign.*;
import crab.newton.internal.*;
/**
 * {@snippet :
 * void (*NewtonFractureCompoundCollisionOnEmitChunk)(struct NewtonBody* chunkBody,struct NewtonFracturedCompoundMeshPart* fracturexChunkMesh,struct NewtonCollision* fracturedCompountCollision);
 * }
 */
public interface NewtonFractureCompoundCollisionOnEmitChunk {

    void apply(java.lang.foreign.MemorySegment body, java.lang.foreign.MemorySegment mainMesh, java.lang.foreign.MemorySegment fracturedCompountCollision);
    static MemorySegment allocate(NewtonFractureCompoundCollisionOnEmitChunk fi, SegmentScope scope) {
        return RuntimeHelper.upcallStub(constants$11.NewtonFractureCompoundCollisionOnEmitChunk_UP$MH, fi, constants$11.NewtonFractureCompoundCollisionOnEmitChunk$FUNC, scope);
    }
    static NewtonFractureCompoundCollisionOnEmitChunk ofAddress(MemorySegment addr, SegmentScope scope) {
        MemorySegment symbol = MemorySegment.ofAddress(addr.address(), 0, scope);
        return (java.lang.foreign.MemorySegment _body, java.lang.foreign.MemorySegment _mainMesh, java.lang.foreign.MemorySegment _fracturedCompountCollision) -> {
            try {
                constants$11.NewtonFractureCompoundCollisionOnEmitChunk_DOWN$MH.invokeExact(symbol, _body, _mainMesh, _fracturedCompountCollision);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


