package crab.newton.callbacks;// Generated by jextract

import java.lang.foreign.*;
import crab.newton.internal.*;

public interface NewtonConstraintDestructor {

    void apply(java.lang.foreign.MemoryAddress me);
    static MemorySegment allocate(NewtonConstraintDestructor fi, MemorySession session) {
        return RuntimeHelper.upcallStub(NewtonConstraintDestructor.class, fi, constants$17.NewtonConstraintDestructor$FUNC, session);
    }
    static NewtonConstraintDestructor ofAddress(MemoryAddress addr, MemorySession session) {
        MemorySegment symbol = MemorySegment.ofAddress(addr, 0, session);
        return (java.lang.foreign.MemoryAddress _me) -> {
            try {
                constants$17.NewtonConstraintDestructor$MH.invokeExact((Addressable)symbol, (java.lang.foreign.Addressable)_me);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


