// Generated by jextract

package crab.newton.callbacks;

import java.lang.foreign.*;
import crab.newton.internal.*;
/**
 * {@snippet :
 * void (*NewtonBodyDestructor)(struct NewtonBody* body);
 * }
 */
public interface NewtonBodyDestructor {

    void apply(java.lang.foreign.MemorySegment me);
    static MemorySegment allocate(NewtonBodyDestructor fi, SegmentScope scope) {
        return RuntimeHelper.upcallStub(constants$10.NewtonBodyDestructor_UP$MH, fi, constants$10.NewtonBodyDestructor$FUNC, scope);
    }
    static NewtonBodyDestructor ofAddress(MemorySegment addr, SegmentScope scope) {
        MemorySegment symbol = MemorySegment.ofAddress(addr.address(), 0, scope);
        return (java.lang.foreign.MemorySegment _me) -> {
            try {
                constants$10.NewtonBodyDestructor_DOWN$MH.invokeExact(symbol, _me);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


