// Generated by jextract

package crab.newton.callbacks;

import java.lang.foreign.*;
import crab.newton.internal.*;
/**
 * {@snippet :
 * void (*NewtonSerializeCallback)(void* serializeHandle,void* buffer,int size);
 * }
 */
public interface NewtonSerializeCallback {

    void apply(java.lang.foreign.MemorySegment world, java.lang.foreign.MemorySegment userData, int threadIndex);
    static MemorySegment allocate(NewtonSerializeCallback fi, SegmentScope scope) {
        return RuntimeHelper.upcallStub(constants$3.NewtonSerializeCallback_UP$MH, fi, constants$3.NewtonSerializeCallback$FUNC, scope);
    }
    static NewtonSerializeCallback ofAddress(MemorySegment addr, SegmentScope scope) {
        MemorySegment symbol = MemorySegment.ofAddress(addr.address(), 0, scope);
        return (java.lang.foreign.MemorySegment _world, java.lang.foreign.MemorySegment _userData, int _threadIndex) -> {
            try {
                constants$3.NewtonSerializeCallback_DOWN$MH.invokeExact(symbol, _world, _userData, _threadIndex);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


