// Generated by jextract

package crab.newton.callbacks;

import java.lang.foreign.*;
import crab.newton.internal.*;
/**
 * {@snippet :
 * float (*NewtonWorldRayFilterCallback)(struct NewtonBody* body,struct NewtonCollision* shapeHit,float* hitContact,float* hitNormal,long long collisionID,void* userData,float intersectParam);
 * }
 */
public interface NewtonWorldRayFilterCallback {

    float apply(java.lang.foreign.MemorySegment body, java.lang.foreign.MemorySegment shapeHit, java.lang.foreign.MemorySegment hitContact, java.lang.foreign.MemorySegment hitNormal, long collisionID, java.lang.foreign.MemorySegment userData, float intersectParam);
    static MemorySegment allocate(NewtonWorldRayFilterCallback fi, SegmentScope scope) {
        return RuntimeHelper.upcallStub(constants$12.NewtonWorldRayFilterCallback_UP$MH, fi, constants$12.NewtonWorldRayFilterCallback$FUNC, scope);
    }
    static NewtonWorldRayFilterCallback ofAddress(MemorySegment addr, SegmentScope scope) {
        MemorySegment symbol = MemorySegment.ofAddress(addr.address(), 0, scope);
        return (java.lang.foreign.MemorySegment _body, java.lang.foreign.MemorySegment _shapeHit, java.lang.foreign.MemorySegment _hitContact, java.lang.foreign.MemorySegment _hitNormal, long _collisionID, java.lang.foreign.MemorySegment _userData, float _intersectParam) -> {
            try {
                return (float)constants$12.NewtonWorldRayFilterCallback_DOWN$MH.invokeExact(symbol, _body, _shapeHit, _hitContact, _hitNormal, _collisionID, _userData, _intersectParam);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


