// Generated by jextract

package crab.newton.callbacks;

import java.lang.foreign.*;
import crab.newton.internal.*;
/**
 * {@snippet :
 * void (*NewtonFractureCompoundCollisionOnEmitCompoundFractured)(struct NewtonBody* fracturedBody);
 * }
 */
public interface NewtonFractureCompoundCollisionOnEmitCompoundFractured {

    void apply(java.lang.foreign.MemorySegment me);
    static MemorySegment allocate(NewtonFractureCompoundCollisionOnEmitCompoundFractured fi, SegmentScope scope) {
        return RuntimeHelper.upcallStub(constants$11.NewtonFractureCompoundCollisionOnEmitCompoundFractured_UP$MH, fi, constants$11.NewtonFractureCompoundCollisionOnEmitCompoundFractured$FUNC, scope);
    }
    static NewtonFractureCompoundCollisionOnEmitCompoundFractured ofAddress(MemorySegment addr, SegmentScope scope) {
        MemorySegment symbol = MemorySegment.ofAddress(addr.address(), 0, scope);
        return (java.lang.foreign.MemorySegment _me) -> {
            try {
                constants$11.NewtonFractureCompoundCollisionOnEmitCompoundFractured_DOWN$MH.invokeExact(symbol, _me);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


