// Generated by jextract

package crab.newton.callbacks;

import java.lang.foreign.*;
import crab.newton.internal.*;
/**
 * {@snippet :
 * void (*NewtonUserBilateralGetInfoCallback)(struct NewtonJoint* userJoint,struct NewtonJointRecord* info);
 * }
 */
public interface NewtonUserBilateralGetInfoCallback {

    void apply(java.lang.foreign.MemorySegment userJoint, java.lang.foreign.MemorySegment info);
    static MemorySegment allocate(NewtonUserBilateralGetInfoCallback fi, SegmentScope scope) {
        return RuntimeHelper.upcallStub(constants$17.NewtonUserBilateralGetInfoCallback_UP$MH, fi, constants$17.NewtonUserBilateralGetInfoCallback$FUNC, scope);
    }
    static NewtonUserBilateralGetInfoCallback ofAddress(MemorySegment addr, SegmentScope scope) {
        MemorySegment symbol = MemorySegment.ofAddress(addr.address(), 0, scope);
        return (java.lang.foreign.MemorySegment _userJoint, java.lang.foreign.MemorySegment _info) -> {
            try {
                constants$17.NewtonUserBilateralGetInfoCallback_DOWN$MH.invokeExact(symbol, _userJoint, _info);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


