// Generated by jextract

package crab.newton.callbacks;

import java.lang.foreign.*;
import crab.newton.internal.*;
/**
 * {@snippet :
 * float (*NewtonCollisionTreeRayCastCallback)(struct NewtonBody* body,struct NewtonCollision* treeCollision,float intersection,float* normal,int faceId,void* usedData);
 * }
 */
public interface NewtonCollisionTreeRayCastCallback {

    float apply(java.lang.foreign.MemorySegment body, java.lang.foreign.MemorySegment treeCollision, float intersection, java.lang.foreign.MemorySegment normal, int faceId, java.lang.foreign.MemorySegment usedData);
    static MemorySegment allocate(NewtonCollisionTreeRayCastCallback fi, SegmentScope scope) {
        return RuntimeHelper.upcallStub(constants$8.NewtonCollisionTreeRayCastCallback_UP$MH, fi, constants$8.NewtonCollisionTreeRayCastCallback$FUNC, scope);
    }
    static NewtonCollisionTreeRayCastCallback ofAddress(MemorySegment addr, SegmentScope scope) {
        MemorySegment symbol = MemorySegment.ofAddress(addr.address(), 0, scope);
        return (java.lang.foreign.MemorySegment _body, java.lang.foreign.MemorySegment _treeCollision, float _intersection, java.lang.foreign.MemorySegment _normal, int _faceId, java.lang.foreign.MemorySegment _usedData) -> {
            try {
                return (float)constants$8.NewtonCollisionTreeRayCastCallback_DOWN$MH.invokeExact(symbol, _body, _treeCollision, _intersection, _normal, _faceId, _usedData);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


