package crab.newton;// Generated by jextract

import java.lang.invoke.VarHandle;
import java.lang.foreign.*;
import crab.newton.internal.*;

public class NewtonChamferCylinderParam {

    static final  GroupLayout $struct$LAYOUT = MemoryLayout.structLayout(
        Constants$root.C_FLOAT$LAYOUT.withName("m_radio"),
        Constants$root.C_FLOAT$LAYOUT.withName("m_height")
    ).withName("crab.newton.NewtonChamferCylinderParam");
    public static MemoryLayout $LAYOUT() {
        return NewtonChamferCylinderParam.$struct$LAYOUT;
    }
    static final VarHandle m_radio$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("m_radio"));
    public static VarHandle m_radio$VH() {
        return NewtonChamferCylinderParam.m_radio$VH;
    }
    public static float m_radio$get(MemorySegment seg) {
        return (float)NewtonChamferCylinderParam.m_radio$VH.get(seg);
    }
    public static void m_radio$set( MemorySegment seg, float x) {
        NewtonChamferCylinderParam.m_radio$VH.set(seg, x);
    }
    public static float m_radio$get(MemorySegment seg, long index) {
        return (float)NewtonChamferCylinderParam.m_radio$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void m_radio$set(MemorySegment seg, long index, float x) {
        NewtonChamferCylinderParam.m_radio$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle m_height$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("m_height"));
    public static VarHandle m_height$VH() {
        return NewtonChamferCylinderParam.m_height$VH;
    }
    public static float m_height$get(MemorySegment seg) {
        return (float)NewtonChamferCylinderParam.m_height$VH.get(seg);
    }
    public static void m_height$set( MemorySegment seg, float x) {
        NewtonChamferCylinderParam.m_height$VH.set(seg, x);
    }
    public static float m_height$get(MemorySegment seg, long index) {
        return (float)NewtonChamferCylinderParam.m_height$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void m_height$set(MemorySegment seg, long index, float x) {
        NewtonChamferCylinderParam.m_height$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(int len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemoryAddress addr, MemorySession session) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, session); }
}


